/*
Copyright 2019 Cisco Systems

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inv_xml_fru_info.proto

package cisco_ios_xr_plat_chas_invmgr_oper_platform_inventory_racks_rack_slots_slot_cards_card_port_slots_port_slot_portses_ports_hw_components_hw_component_sensors_sensor_attributes_fru_info

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvXmlFruInfo_KEYS struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Name_1               string   `protobuf:"bytes,2,opt,name=name_1,json=name1,proto3" json:"name_1,omitempty"`
	Name_2               string   `protobuf:"bytes,3,opt,name=name_2,json=name2,proto3" json:"name_2,omitempty"`
	Name_3               string   `protobuf:"bytes,4,opt,name=name_3,json=name3,proto3" json:"name_3,omitempty"`
	Name_4               string   `protobuf:"bytes,5,opt,name=name_4,json=name4,proto3" json:"name_4,omitempty"`
	Name_5               string   `protobuf:"bytes,6,opt,name=name_5,json=name5,proto3" json:"name_5,omitempty"`
	Name_6               string   `protobuf:"bytes,7,opt,name=name_6,json=name6,proto3" json:"name_6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvXmlFruInfo_KEYS) Reset()         { *m = InvXmlFruInfo_KEYS{} }
func (m *InvXmlFruInfo_KEYS) String() string { return proto.CompactTextString(m) }
func (*InvXmlFruInfo_KEYS) ProtoMessage()    {}
func (*InvXmlFruInfo_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c4a3ece7c164817, []int{0}
}

func (m *InvXmlFruInfo_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvXmlFruInfo_KEYS.Unmarshal(m, b)
}
func (m *InvXmlFruInfo_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvXmlFruInfo_KEYS.Marshal(b, m, deterministic)
}
func (m *InvXmlFruInfo_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvXmlFruInfo_KEYS.Merge(m, src)
}
func (m *InvXmlFruInfo_KEYS) XXX_Size() int {
	return xxx_messageInfo_InvXmlFruInfo_KEYS.Size(m)
}
func (m *InvXmlFruInfo_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_InvXmlFruInfo_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_InvXmlFruInfo_KEYS proto.InternalMessageInfo

func (m *InvXmlFruInfo_KEYS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InvXmlFruInfo_KEYS) GetName_1() string {
	if m != nil {
		return m.Name_1
	}
	return ""
}

func (m *InvXmlFruInfo_KEYS) GetName_2() string {
	if m != nil {
		return m.Name_2
	}
	return ""
}

func (m *InvXmlFruInfo_KEYS) GetName_3() string {
	if m != nil {
		return m.Name_3
	}
	return ""
}

func (m *InvXmlFruInfo_KEYS) GetName_4() string {
	if m != nil {
		return m.Name_4
	}
	return ""
}

func (m *InvXmlFruInfo_KEYS) GetName_5() string {
	if m != nil {
		return m.Name_5
	}
	return ""
}

func (m *InvXmlFruInfo_KEYS) GetName_6() string {
	if m != nil {
		return m.Name_6
	}
	return ""
}

type InvTimespec struct {
	TimeInSeconds        int32    `protobuf:"zigzag32,1,opt,name=time_in_seconds,json=timeInSeconds,proto3" json:"time_in_seconds,omitempty"`
	TimeInNanoSeconds    int32    `protobuf:"zigzag32,2,opt,name=time_in_nano_seconds,json=timeInNanoSeconds,proto3" json:"time_in_nano_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvTimespec) Reset()         { *m = InvTimespec{} }
func (m *InvTimespec) String() string { return proto.CompactTextString(m) }
func (*InvTimespec) ProtoMessage()    {}
func (*InvTimespec) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c4a3ece7c164817, []int{1}
}

func (m *InvTimespec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvTimespec.Unmarshal(m, b)
}
func (m *InvTimespec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvTimespec.Marshal(b, m, deterministic)
}
func (m *InvTimespec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvTimespec.Merge(m, src)
}
func (m *InvTimespec) XXX_Size() int {
	return xxx_messageInfo_InvTimespec.Size(m)
}
func (m *InvTimespec) XXX_DiscardUnknown() {
	xxx_messageInfo_InvTimespec.DiscardUnknown(m)
}

var xxx_messageInfo_InvTimespec proto.InternalMessageInfo

func (m *InvTimespec) GetTimeInSeconds() int32 {
	if m != nil {
		return m.TimeInSeconds
	}
	return 0
}

func (m *InvTimespec) GetTimeInNanoSeconds() int32 {
	if m != nil {
		return m.TimeInNanoSeconds
	}
	return 0
}

type InvXmlFruInfo struct {
	ModuleAdministrativeState      string       `protobuf:"bytes,50,opt,name=module_administrative_state,json=moduleAdministrativeState,proto3" json:"module_administrative_state,omitempty"`
	ModulePowerAdministrativeState string       `protobuf:"bytes,51,opt,name=module_power_administrative_state,json=modulePowerAdministrativeState,proto3" json:"module_power_administrative_state,omitempty"`
	ModuleOperationalState         string       `protobuf:"bytes,52,opt,name=module_operational_state,json=moduleOperationalState,proto3" json:"module_operational_state,omitempty"`
	ModuleMonitorState             string       `protobuf:"bytes,53,opt,name=module_monitor_state,json=moduleMonitorState,proto3" json:"module_monitor_state,omitempty"`
	ModuleResetReason              string       `protobuf:"bytes,54,opt,name=module_reset_reason,json=moduleResetReason,proto3" json:"module_reset_reason,omitempty"`
	LastOperationalStateChange     *InvTimespec `protobuf:"bytes,55,opt,name=last_operational_state_change,json=lastOperationalStateChange,proto3" json:"last_operational_state_change,omitempty"`
	ModuleUpTime                   *InvTimespec `protobuf:"bytes,56,opt,name=module_up_time,json=moduleUpTime,proto3" json:"module_up_time,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}     `json:"-"`
	XXX_unrecognized               []byte       `json:"-"`
	XXX_sizecache                  int32        `json:"-"`
}

func (m *InvXmlFruInfo) Reset()         { *m = InvXmlFruInfo{} }
func (m *InvXmlFruInfo) String() string { return proto.CompactTextString(m) }
func (*InvXmlFruInfo) ProtoMessage()    {}
func (*InvXmlFruInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c4a3ece7c164817, []int{2}
}

func (m *InvXmlFruInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvXmlFruInfo.Unmarshal(m, b)
}
func (m *InvXmlFruInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvXmlFruInfo.Marshal(b, m, deterministic)
}
func (m *InvXmlFruInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvXmlFruInfo.Merge(m, src)
}
func (m *InvXmlFruInfo) XXX_Size() int {
	return xxx_messageInfo_InvXmlFruInfo.Size(m)
}
func (m *InvXmlFruInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InvXmlFruInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InvXmlFruInfo proto.InternalMessageInfo

func (m *InvXmlFruInfo) GetModuleAdministrativeState() string {
	if m != nil {
		return m.ModuleAdministrativeState
	}
	return ""
}

func (m *InvXmlFruInfo) GetModulePowerAdministrativeState() string {
	if m != nil {
		return m.ModulePowerAdministrativeState
	}
	return ""
}

func (m *InvXmlFruInfo) GetModuleOperationalState() string {
	if m != nil {
		return m.ModuleOperationalState
	}
	return ""
}

func (m *InvXmlFruInfo) GetModuleMonitorState() string {
	if m != nil {
		return m.ModuleMonitorState
	}
	return ""
}

func (m *InvXmlFruInfo) GetModuleResetReason() string {
	if m != nil {
		return m.ModuleResetReason
	}
	return ""
}

func (m *InvXmlFruInfo) GetLastOperationalStateChange() *InvTimespec {
	if m != nil {
		return m.LastOperationalStateChange
	}
	return nil
}

func (m *InvXmlFruInfo) GetModuleUpTime() *InvTimespec {
	if m != nil {
		return m.ModuleUpTime
	}
	return nil
}

func init() {
	proto.RegisterType((*InvXmlFruInfo_KEYS)(nil), "cisco_ios_xr_plat_chas_invmgr_oper.platform_inventory.racks.rack.slots.slot.cards.card.port_slots.port_slot.portses.ports.hw_components.hw_component.sensors.sensor.attributes.fru_info.inv_xml_fru_info_KEYS")
	proto.RegisterType((*InvTimespec)(nil), "cisco_ios_xr_plat_chas_invmgr_oper.platform_inventory.racks.rack.slots.slot.cards.card.port_slots.port_slot.portses.ports.hw_components.hw_component.sensors.sensor.attributes.fru_info.inv_timespec")
	proto.RegisterType((*InvXmlFruInfo)(nil), "cisco_ios_xr_plat_chas_invmgr_oper.platform_inventory.racks.rack.slots.slot.cards.card.port_slots.port_slot.portses.ports.hw_components.hw_component.sensors.sensor.attributes.fru_info.inv_xml_fru_info")
}

func init() { proto.RegisterFile("inv_xml_fru_info.proto", fileDescriptor_4c4a3ece7c164817) }

var fileDescriptor_4c4a3ece7c164817 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0x86, 0x35, 0xa1, 0x0d, 0xc2, 0x94, 0x4b, 0x4c, 0x5b, 0x19, 0x10, 0xa8, 0x64, 0x81, 0xba,
	0x32, 0x34, 0x37, 0xba, 0x42, 0x42, 0x88, 0x45, 0x85, 0xb8, 0x68, 0x02, 0x0b, 0x56, 0x96, 0x3b,
	0x71, 0x52, 0x8b, 0xb1, 0xcf, 0xc8, 0xc7, 0x49, 0xcb, 0x23, 0xf0, 0x3e, 0x20, 0x9e, 0x80, 0xb7,
	0xe1, 0x21, 0x90, 0xed, 0xe9, 0x0c, 0x84, 0xbe, 0x00, 0xdd, 0x78, 0x3c, 0xdf, 0xff, 0xff, 0x47,
	0xe7, 0x58, 0xe3, 0x21, 0xbb, 0xda, 0xae, 0xc4, 0x99, 0x29, 0xc5, 0xdc, 0x2d, 0x85, 0xb6, 0x73,
	0xe0, 0x95, 0x03, 0x0f, 0xf4, 0x47, 0x56, 0x68, 0x2c, 0x40, 0x68, 0x40, 0x71, 0xe6, 0x44, 0x55,
	0x4a, 0x2f, 0x8a, 0x13, 0x89, 0x42, 0xdb, 0x95, 0x59, 0x38, 0x01, 0x95, 0x72, 0x3c, 0xd0, 0x39,
	0x38, 0x13, 0xa0, 0xb2, 0x1e, 0xdc, 0x17, 0xee, 0x64, 0xf1, 0x19, 0xe3, 0xca, 0xb1, 0x04, 0x8f,
	0x71, 0xe5, 0x85, 0x74, 0x33, 0x8c, 0x2b, 0xaf, 0xc0, 0x79, 0x91, 0xa4, 0x66, 0x1b, 0x77, 0xa8,
	0x12, 0x41, 0x7e, 0x72, 0x2a, 0x0a, 0x30, 0x15, 0x58, 0x65, 0xd7, 0xde, 0x38, 0x2a, 0x8b, 0xe0,
	0xb0, 0x7e, 0x72, 0xe9, 0xbd, 0xd3, 0xc7, 0x4b, 0xaf, 0x90, 0x9f, 0xf7, 0xdf, 0xff, 0x9e, 0x91,
	0x9d, 0xf5, 0xa1, 0xc4, 0xeb, 0x57, 0x9f, 0xa6, 0x94, 0x92, 0x0d, 0x2b, 0x8d, 0x62, 0xd9, 0x5e,
	0xb6, 0x7f, 0x2d, 0x8f, 0x7b, 0xba, 0x43, 0xba, 0xe1, 0x29, 0x0e, 0x58, 0x27, 0xd2, 0xcd, 0xf0,
	0x76, 0xd0, 0xe0, 0x01, 0xbb, 0xd2, 0xe2, 0x41, 0x83, 0x87, 0x6c, 0xa3, 0xc5, 0xc3, 0x06, 0x8f,
	0xd8, 0x66, 0x8b, 0x47, 0x0d, 0x1e, 0xb3, 0x6e, 0x8b, 0xc7, 0x0d, 0x9e, 0xb0, 0xab, 0x2d, 0x9e,
	0xf4, 0x17, 0x64, 0x2b, 0xb4, 0xed, 0xb5, 0x51, 0x58, 0xa9, 0x82, 0x3e, 0x26, 0xb7, 0xc2, 0x5e,
	0x68, 0x2b, 0x50, 0x15, 0x60, 0x67, 0x18, 0x1b, 0xef, 0xe5, 0x37, 0x02, 0x3e, 0xb2, 0xd3, 0x04,
	0xe9, 0x13, 0xb2, 0x7d, 0xee, 0xb3, 0xd2, 0x42, 0x63, 0xee, 0x44, 0x73, 0x2f, 0x99, 0xdf, 0x4a,
	0x0b, 0x75, 0xa0, 0xff, 0xad, 0x4b, 0x6e, 0xaf, 0x1f, 0x10, 0x7d, 0x4e, 0xee, 0x1b, 0x98, 0x2d,
	0x4b, 0x25, 0xe4, 0xcc, 0x68, 0xab, 0xd1, 0x3b, 0xe9, 0xf5, 0x4a, 0x09, 0xf4, 0xd2, 0x2b, 0x36,
	0x88, 0x9d, 0xde, 0x4d, 0x96, 0x17, 0x7f, 0x39, 0xa6, 0xc1, 0x40, 0x8f, 0xc8, 0xa3, 0x3a, 0x5f,
	0xc1, 0xa9, 0x72, 0x17, 0x57, 0x19, 0xc6, 0x2a, 0x0f, 0x93, 0xf1, 0x7d, 0xf0, 0x5d, 0x54, 0xea,
	0x90, 0xb0, 0xba, 0x54, 0xf8, 0xc8, 0xa4, 0xd7, 0x60, 0x65, 0x59, 0x57, 0x18, 0xc5, 0x0a, 0xbb,
	0x49, 0x7f, 0xd7, 0xca, 0x29, 0xf9, 0x94, 0x6c, 0xd7, 0x49, 0x03, 0x56, 0x7b, 0x70, 0x75, 0x6a,
	0x1c, 0x53, 0x34, 0x69, 0x6f, 0x92, 0x94, 0x12, 0x9c, 0xdc, 0xa9, 0x13, 0x4e, 0xa1, 0xf2, 0xc2,
	0x29, 0x89, 0x60, 0xd9, 0x24, 0x06, 0x7a, 0x49, 0xca, 0x83, 0x92, 0x47, 0x81, 0x7e, 0xed, 0x90,
	0x07, 0xa5, 0x44, 0xff, 0x6f, 0x6b, 0xe1, 0x76, 0xd8, 0x85, 0x62, 0xcf, 0xf6, 0xb2, 0xfd, 0xeb,
	0x83, 0x9f, 0x19, 0xff, 0x4f, 0xef, 0x0f, 0xff, 0xf3, 0x23, 0xcc, 0xef, 0x85, 0x61, 0xd7, 0xcf,
	0xf9, 0x65, 0x9c, 0x94, 0xfe, 0xca, 0xc8, 0xcd, 0xfa, 0xf0, 0x96, 0x55, 0x8c, 0xb0, 0xc3, 0x4b,
	0x35, 0xfc, 0x56, 0x9a, 0xee, 0x63, 0xf5, 0x41, 0x1b, 0x75, 0xdc, 0x8d, 0x3f, 0xc6, 0xe1, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x23, 0x20, 0xcd, 0x32, 0x05, 0x00, 0x00,
}
