/*
Copyright 2019 Cisco Systems

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ldp_neighbor_brief_info.proto

package cisco_ios_xr_mpls_ldp_oper_mpls_ldp_global_standby_vrfs_vrf_neighbor_briefs_neighbor_brief

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LdpNeighborBriefInfo_KEYS struct {
	VrfName              string   `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	LsrId                string   `protobuf:"bytes,2,opt,name=lsr_id,json=lsrId,proto3" json:"lsr_id,omitempty"`
	LabelSpaceId         uint32   `protobuf:"varint,3,opt,name=label_space_id,json=labelSpaceId,proto3" json:"label_space_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LdpNeighborBriefInfo_KEYS) Reset()         { *m = LdpNeighborBriefInfo_KEYS{} }
func (m *LdpNeighborBriefInfo_KEYS) String() string { return proto.CompactTextString(m) }
func (*LdpNeighborBriefInfo_KEYS) ProtoMessage()    {}
func (*LdpNeighborBriefInfo_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_57a8ad7f03439cf8, []int{0}
}

func (m *LdpNeighborBriefInfo_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LdpNeighborBriefInfo_KEYS.Unmarshal(m, b)
}
func (m *LdpNeighborBriefInfo_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LdpNeighborBriefInfo_KEYS.Marshal(b, m, deterministic)
}
func (m *LdpNeighborBriefInfo_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LdpNeighborBriefInfo_KEYS.Merge(m, src)
}
func (m *LdpNeighborBriefInfo_KEYS) XXX_Size() int {
	return xxx_messageInfo_LdpNeighborBriefInfo_KEYS.Size(m)
}
func (m *LdpNeighborBriefInfo_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_LdpNeighborBriefInfo_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_LdpNeighborBriefInfo_KEYS proto.InternalMessageInfo

func (m *LdpNeighborBriefInfo_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *LdpNeighborBriefInfo_KEYS) GetLsrId() string {
	if m != nil {
		return m.LsrId
	}
	return ""
}

func (m *LdpNeighborBriefInfo_KEYS) GetLabelSpaceId() uint32 {
	if m != nil {
		return m.LabelSpaceId
	}
	return 0
}

type LdpVrfInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LdpVrfInfo) Reset()         { *m = LdpVrfInfo{} }
func (m *LdpVrfInfo) String() string { return proto.CompactTextString(m) }
func (*LdpVrfInfo) ProtoMessage()    {}
func (*LdpVrfInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_57a8ad7f03439cf8, []int{1}
}

func (m *LdpVrfInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LdpVrfInfo.Unmarshal(m, b)
}
func (m *LdpVrfInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LdpVrfInfo.Marshal(b, m, deterministic)
}
func (m *LdpVrfInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LdpVrfInfo.Merge(m, src)
}
func (m *LdpVrfInfo) XXX_Size() int {
	return xxx_messageInfo_LdpVrfInfo.Size(m)
}
func (m *LdpVrfInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LdpVrfInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LdpVrfInfo proto.InternalMessageInfo

func (m *LdpVrfInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LdpVrfInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LdpNeighborBriefAfInfo struct {
	AddressFamily        string   `protobuf:"bytes,1,opt,name=address_family,json=addressFamily,proto3" json:"address_family,omitempty"`
	NumOfNbrDiscovery    uint32   `protobuf:"varint,2,opt,name=num_of_nbr_discovery,json=numOfNbrDiscovery,proto3" json:"num_of_nbr_discovery,omitempty"`
	NumOfNbrAddresses    uint32   `protobuf:"varint,3,opt,name=num_of_nbr_addresses,json=numOfNbrAddresses,proto3" json:"num_of_nbr_addresses,omitempty"`
	NumOfNbrLbl          uint32   `protobuf:"varint,4,opt,name=num_of_nbr_lbl,json=numOfNbrLbl,proto3" json:"num_of_nbr_lbl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LdpNeighborBriefAfInfo) Reset()         { *m = LdpNeighborBriefAfInfo{} }
func (m *LdpNeighborBriefAfInfo) String() string { return proto.CompactTextString(m) }
func (*LdpNeighborBriefAfInfo) ProtoMessage()    {}
func (*LdpNeighborBriefAfInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_57a8ad7f03439cf8, []int{2}
}

func (m *LdpNeighborBriefAfInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LdpNeighborBriefAfInfo.Unmarshal(m, b)
}
func (m *LdpNeighborBriefAfInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LdpNeighborBriefAfInfo.Marshal(b, m, deterministic)
}
func (m *LdpNeighborBriefAfInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LdpNeighborBriefAfInfo.Merge(m, src)
}
func (m *LdpNeighborBriefAfInfo) XXX_Size() int {
	return xxx_messageInfo_LdpNeighborBriefAfInfo.Size(m)
}
func (m *LdpNeighborBriefAfInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LdpNeighborBriefAfInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LdpNeighborBriefAfInfo proto.InternalMessageInfo

func (m *LdpNeighborBriefAfInfo) GetAddressFamily() string {
	if m != nil {
		return m.AddressFamily
	}
	return ""
}

func (m *LdpNeighborBriefAfInfo) GetNumOfNbrDiscovery() uint32 {
	if m != nil {
		return m.NumOfNbrDiscovery
	}
	return 0
}

func (m *LdpNeighborBriefAfInfo) GetNumOfNbrAddresses() uint32 {
	if m != nil {
		return m.NumOfNbrAddresses
	}
	return 0
}

func (m *LdpNeighborBriefAfInfo) GetNumOfNbrLbl() uint32 {
	if m != nil {
		return m.NumOfNbrLbl
	}
	return 0
}

type LdpNeighborBriefInfo struct {
	Vrf                   *LdpVrfInfo               `protobuf:"bytes,50,opt,name=vrf,proto3" json:"vrf,omitempty"`
	IsGracefulRestartable bool                      `protobuf:"varint,51,opt,name=is_graceful_restartable,json=isGracefulRestartable,proto3" json:"is_graceful_restartable,omitempty"`
	NsrState              string                    `protobuf:"bytes,52,opt,name=nsr_state,json=nsrState,proto3" json:"nsr_state,omitempty"`
	UpTimeSeconds         uint32                    `protobuf:"varint,53,opt,name=up_time_seconds,json=upTimeSeconds,proto3" json:"up_time_seconds,omitempty"`
	NbrBrAfInfo           []*LdpNeighborBriefAfInfo `protobuf:"bytes,54,rep,name=nbr_br_af_info,json=nbrBrAfInfo,proto3" json:"nbr_br_af_info,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *LdpNeighborBriefInfo) Reset()         { *m = LdpNeighborBriefInfo{} }
func (m *LdpNeighborBriefInfo) String() string { return proto.CompactTextString(m) }
func (*LdpNeighborBriefInfo) ProtoMessage()    {}
func (*LdpNeighborBriefInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_57a8ad7f03439cf8, []int{3}
}

func (m *LdpNeighborBriefInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LdpNeighborBriefInfo.Unmarshal(m, b)
}
func (m *LdpNeighborBriefInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LdpNeighborBriefInfo.Marshal(b, m, deterministic)
}
func (m *LdpNeighborBriefInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LdpNeighborBriefInfo.Merge(m, src)
}
func (m *LdpNeighborBriefInfo) XXX_Size() int {
	return xxx_messageInfo_LdpNeighborBriefInfo.Size(m)
}
func (m *LdpNeighborBriefInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LdpNeighborBriefInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LdpNeighborBriefInfo proto.InternalMessageInfo

func (m *LdpNeighborBriefInfo) GetVrf() *LdpVrfInfo {
	if m != nil {
		return m.Vrf
	}
	return nil
}

func (m *LdpNeighborBriefInfo) GetIsGracefulRestartable() bool {
	if m != nil {
		return m.IsGracefulRestartable
	}
	return false
}

func (m *LdpNeighborBriefInfo) GetNsrState() string {
	if m != nil {
		return m.NsrState
	}
	return ""
}

func (m *LdpNeighborBriefInfo) GetUpTimeSeconds() uint32 {
	if m != nil {
		return m.UpTimeSeconds
	}
	return 0
}

func (m *LdpNeighborBriefInfo) GetNbrBrAfInfo() []*LdpNeighborBriefAfInfo {
	if m != nil {
		return m.NbrBrAfInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*LdpNeighborBriefInfo_KEYS)(nil), "cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_briefs.neighbor_brief.ldp_neighbor_brief_info_KEYS")
	proto.RegisterType((*LdpVrfInfo)(nil), "cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_briefs.neighbor_brief.ldp_vrf_info")
	proto.RegisterType((*LdpNeighborBriefAfInfo)(nil), "cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_briefs.neighbor_brief.ldp_neighbor_brief_af_info")
	proto.RegisterType((*LdpNeighborBriefInfo)(nil), "cisco_ios_xr_mpls_ldp_oper.mpls_ldp.global.standby.vrfs.vrf.neighbor_briefs.neighbor_brief.ldp_neighbor_brief_info")
}

func init() { proto.RegisterFile("ldp_neighbor_brief_info.proto", fileDescriptor_57a8ad7f03439cf8) }

var fileDescriptor_57a8ad7f03439cf8 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x5d, 0x6f, 0xd3, 0x3c,
	0x18, 0x55, 0xda, 0xbd, 0x7b, 0x3b, 0x77, 0x2d, 0xc2, 0x62, 0x5a, 0xf8, 0x92, 0xaa, 0xf2, 0xa1,
	0x5e, 0x05, 0xa9, 0x83, 0xdd, 0x0f, 0xf1, 0xa1, 0x0a, 0x34, 0xa4, 0x94, 0x1b, 0xb8, 0x79, 0x64,
	0xd7, 0x76, 0x67, 0xc9, 0xb1, 0xa3, 0xe7, 0x49, 0x22, 0xca, 0x5f, 0xe1, 0x4f, 0xf0, 0x3b, 0xf8,
	0x55, 0xc8, 0x59, 0x0a, 0x65, 0xda, 0x2e, 0x77, 0x13, 0xe5, 0x39, 0xc7, 0xe7, 0x1c, 0xe7, 0x38,
	0x66, 0x8f, 0x9d, 0x2a, 0xc1, 0x6b, 0xbb, 0xbe, 0x90, 0x01, 0x41, 0xa2, 0xd5, 0x06, 0xac, 0x37,
	0x21, 0x2b, 0x31, 0x54, 0x81, 0x7f, 0x5d, 0x59, 0x5a, 0x05, 0xb0, 0x81, 0xe0, 0x1b, 0x42, 0x51,
	0x3a, 0x82, 0x28, 0x08, 0xa5, 0xc6, 0x6c, 0x3b, 0x65, 0x6b, 0x17, 0xa4, 0x70, 0x19, 0x55, 0xc2,
	0x2b, 0xb9, 0xc9, 0x1a, 0x34, 0x14, 0x1f, 0xd9, 0xbf, 0xb6, 0x74, 0x65, 0x9e, 0x36, 0xec, 0xd1,
	0x0d, 0xe1, 0xf0, 0xe1, 0xed, 0x97, 0x25, 0xbf, 0xcf, 0x06, 0x0d, 0x1a, 0xf0, 0xa2, 0xd0, 0x69,
	0x32, 0x49, 0x66, 0x07, 0xf9, 0xff, 0x0d, 0x9a, 0x73, 0x51, 0x68, 0x7e, 0xc4, 0xf6, 0x1d, 0x21,
	0x58, 0x95, 0xf6, 0x5a, 0xe2, 0x3f, 0x47, 0xb8, 0x50, 0xfc, 0x29, 0x1b, 0x3b, 0x21, 0xb5, 0x03,
	0x2a, 0xc5, 0x4a, 0x47, 0xba, 0x3f, 0x49, 0x66, 0xa3, 0xfc, 0xb0, 0x45, 0x97, 0x11, 0x5c, 0xa8,
	0xe9, 0x9c, 0x1d, 0xc6, 0xdc, 0xe8, 0x1d, 0xc3, 0x38, 0x67, 0x7b, 0x3b, 0x19, 0xed, 0x3b, 0x1f,
	0xb3, 0x5e, 0x67, 0x3e, 0xca, 0x7b, 0x56, 0x4d, 0x7f, 0x25, 0xec, 0xc1, 0x35, 0x9b, 0x15, 0x9d,
	0xc5, 0x33, 0x36, 0x16, 0x4a, 0xa1, 0x26, 0x02, 0x23, 0x0a, 0xeb, 0x36, 0x9d, 0xd9, 0xa8, 0x43,
	0xdf, 0xb5, 0x20, 0x7f, 0xc1, 0xee, 0xf9, 0xba, 0x80, 0x60, 0xc0, 0x4b, 0x04, 0x15, 0xab, 0x6d,
	0x34, 0x6e, 0xba, 0x9c, 0xbb, 0xbe, 0x2e, 0x3e, 0x99, 0x73, 0x89, 0x6f, 0xb6, 0xc4, 0x15, 0x41,
	0x67, 0xa6, 0xa9, 0xfb, 0xac, 0x3f, 0x82, 0xb3, 0x2d, 0xc1, 0x9f, 0xb0, 0xf1, 0x8e, 0xc0, 0x49,
	0x97, 0xee, 0xb5, 0x4b, 0x87, 0xdb, 0xa5, 0x1f, 0xa5, 0x9b, 0xfe, 0xec, 0xb3, 0xe3, 0x1b, 0x9a,
	0xe7, 0xdf, 0x59, 0xbf, 0x41, 0x93, 0xce, 0x27, 0xc9, 0x6c, 0x38, 0xbf, 0xc8, 0x6e, 0xef, 0xf8,
	0xb3, 0xdd, 0x33, 0xc8, 0x63, 0x28, 0x3f, 0x65, 0xc7, 0x96, 0x60, 0x8d, 0x62, 0xa5, 0x4d, 0xed,
	0x00, 0x35, 0x55, 0x02, 0x2b, 0x21, 0x9d, 0x4e, 0x4f, 0x26, 0xc9, 0x6c, 0x90, 0x1f, 0x59, 0x7a,
	0xdf, 0xb1, 0xf9, 0x5f, 0x92, 0x3f, 0x64, 0x07, 0x9e, 0x10, 0xa8, 0x12, 0x95, 0x4e, 0x5f, 0xb6,
	0xc5, 0x0f, 0x3c, 0xe1, 0x32, 0xce, 0xfc, 0x39, 0xbb, 0x53, 0x97, 0x50, 0xd9, 0x42, 0x03, 0xe9,
	0x55, 0xf0, 0x8a, 0xd2, 0x57, 0x6d, 0x25, 0xa3, 0xba, 0xfc, 0x6c, 0x0b, 0xbd, 0xbc, 0x04, 0xf9,
	0x8f, 0x84, 0x8d, 0x63, 0x67, 0xb1, 0xe7, 0xcb, 0x4d, 0xa5, 0xa7, 0x93, 0xfe, 0x6c, 0x38, 0x6f,
	0x6e, 0xbb, 0x84, 0xeb, 0xff, 0xa9, 0x7c, 0xe8, 0x25, 0xbe, 0xc6, 0x33, 0xb3, 0xf0, 0x26, 0xc8,
	0xfd, 0xf6, 0x3a, 0x9e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xef, 0xcd, 0xef, 0x2f, 0xaf, 0x03,
	0x00, 0x00,
}
