/*
Copyright 2019 Cisco Systems

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: show_version_info.proto

package cisco_ios_xr_spirit_install_instmgr_oper_software_install_version

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShowVersionInfo_KEYS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowVersionInfo_KEYS) Reset()         { *m = ShowVersionInfo_KEYS{} }
func (m *ShowVersionInfo_KEYS) String() string { return proto.CompactTextString(m) }
func (*ShowVersionInfo_KEYS) ProtoMessage()    {}
func (*ShowVersionInfo_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b4a0db2255eef, []int{0}
}

func (m *ShowVersionInfo_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowVersionInfo_KEYS.Unmarshal(m, b)
}
func (m *ShowVersionInfo_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowVersionInfo_KEYS.Marshal(b, m, deterministic)
}
func (m *ShowVersionInfo_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowVersionInfo_KEYS.Merge(m, src)
}
func (m *ShowVersionInfo_KEYS) XXX_Size() int {
	return xxx_messageInfo_ShowVersionInfo_KEYS.Size(m)
}
func (m *ShowVersionInfo_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowVersionInfo_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_ShowVersionInfo_KEYS proto.InternalMessageInfo

type VersionPackageList struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuiltBy              string   `protobuf:"bytes,3,opt,name=built_by,json=builtBy,proto3" json:"built_by,omitempty"`
	BuiltOn              string   `protobuf:"bytes,4,opt,name=built_on,json=builtOn,proto3" json:"built_on,omitempty"`
	BuildHost            string   `protobuf:"bytes,5,opt,name=build_host,json=buildHost,proto3" json:"build_host,omitempty"`
	Workspace            string   `protobuf:"bytes,6,opt,name=workspace,proto3" json:"workspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionPackageList) Reset()         { *m = VersionPackageList{} }
func (m *VersionPackageList) String() string { return proto.CompactTextString(m) }
func (*VersionPackageList) ProtoMessage()    {}
func (*VersionPackageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b4a0db2255eef, []int{1}
}

func (m *VersionPackageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionPackageList.Unmarshal(m, b)
}
func (m *VersionPackageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionPackageList.Marshal(b, m, deterministic)
}
func (m *VersionPackageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionPackageList.Merge(m, src)
}
func (m *VersionPackageList) XXX_Size() int {
	return xxx_messageInfo_VersionPackageList.Size(m)
}
func (m *VersionPackageList) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionPackageList.DiscardUnknown(m)
}

var xxx_messageInfo_VersionPackageList proto.InternalMessageInfo

func (m *VersionPackageList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VersionPackageList) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionPackageList) GetBuiltBy() string {
	if m != nil {
		return m.BuiltBy
	}
	return ""
}

func (m *VersionPackageList) GetBuiltOn() string {
	if m != nil {
		return m.BuiltOn
	}
	return ""
}

func (m *VersionPackageList) GetBuildHost() string {
	if m != nil {
		return m.BuildHost
	}
	return ""
}

func (m *VersionPackageList) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

type ShowVersionInfo struct {
	Package              []*VersionPackageList `protobuf:"bytes,50,rep,name=package,proto3" json:"package,omitempty"`
	Location             string                `protobuf:"bytes,51,opt,name=location,proto3" json:"location,omitempty"`
	Label                string                `protobuf:"bytes,52,opt,name=label,proto3" json:"label,omitempty"`
	CopyrightInfo        string                `protobuf:"bytes,53,opt,name=copyright_info,json=copyrightInfo,proto3" json:"copyright_info,omitempty"`
	HardwareInfo         string                `protobuf:"bytes,54,opt,name=hardware_info,json=hardwareInfo,proto3" json:"hardware_info,omitempty"`
	SystemUptime         string                `protobuf:"bytes,55,opt,name=system_uptime,json=systemUptime,proto3" json:"system_uptime,omitempty"`
	ImgInfo              string                `protobuf:"bytes,56,opt,name=img_info,json=imgInfo,proto3" json:"img_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ShowVersionInfo) Reset()         { *m = ShowVersionInfo{} }
func (m *ShowVersionInfo) String() string { return proto.CompactTextString(m) }
func (*ShowVersionInfo) ProtoMessage()    {}
func (*ShowVersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b4a0db2255eef, []int{2}
}

func (m *ShowVersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowVersionInfo.Unmarshal(m, b)
}
func (m *ShowVersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowVersionInfo.Marshal(b, m, deterministic)
}
func (m *ShowVersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowVersionInfo.Merge(m, src)
}
func (m *ShowVersionInfo) XXX_Size() int {
	return xxx_messageInfo_ShowVersionInfo.Size(m)
}
func (m *ShowVersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowVersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShowVersionInfo proto.InternalMessageInfo

func (m *ShowVersionInfo) GetPackage() []*VersionPackageList {
	if m != nil {
		return m.Package
	}
	return nil
}

func (m *ShowVersionInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ShowVersionInfo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ShowVersionInfo) GetCopyrightInfo() string {
	if m != nil {
		return m.CopyrightInfo
	}
	return ""
}

func (m *ShowVersionInfo) GetHardwareInfo() string {
	if m != nil {
		return m.HardwareInfo
	}
	return ""
}

func (m *ShowVersionInfo) GetSystemUptime() string {
	if m != nil {
		return m.SystemUptime
	}
	return ""
}

func (m *ShowVersionInfo) GetImgInfo() string {
	if m != nil {
		return m.ImgInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*ShowVersionInfo_KEYS)(nil), "cisco_ios_xr_spirit_install_instmgr_oper.software_install.version.show_version_info_KEYS")
	proto.RegisterType((*VersionPackageList)(nil), "cisco_ios_xr_spirit_install_instmgr_oper.software_install.version.version_package_list")
	proto.RegisterType((*ShowVersionInfo)(nil), "cisco_ios_xr_spirit_install_instmgr_oper.software_install.version.show_version_info")
}

func init() { proto.RegisterFile("show_version_info.proto", fileDescriptor_c60b4a0db2255eef) }

var fileDescriptor_c60b4a0db2255eef = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4b, 0xeb, 0x40,
	0x10, 0xc0, 0xe9, 0xff, 0x76, 0xde, 0xeb, 0x83, 0xb7, 0x14, 0x5d, 0x45, 0xa1, 0x54, 0x84, 0x9e,
	0x72, 0x68, 0xfd, 0x77, 0x55, 0x10, 0x14, 0x0f, 0x42, 0x45, 0xc4, 0xd3, 0xb2, 0x49, 0xb7, 0xc9,
	0xd2, 0x24, 0x13, 0x77, 0xb7, 0xd6, 0x7c, 0x32, 0xbf, 0x80, 0x1f, 0x4c, 0xb2, 0x9b, 0x54, 0xa1,
	0xde, 0x3c, 0x65, 0xe7, 0xf7, 0x9b, 0x4c, 0x66, 0x66, 0x03, 0xbb, 0x3a, 0xc2, 0x35, 0x7b, 0x15,
	0x4a, 0x4b, 0x4c, 0x99, 0x4c, 0x17, 0xe8, 0x65, 0x0a, 0x0d, 0x92, 0xcb, 0x40, 0xea, 0x00, 0x99,
	0x44, 0xcd, 0xde, 0x14, 0xd3, 0x99, 0x54, 0xd2, 0x30, 0x99, 0x6a, 0xc3, 0xe3, 0xd8, 0x3e, 0x93,
	0x50, 0x31, 0xcc, 0x84, 0xf2, 0x34, 0x2e, 0xcc, 0x9a, 0x2b, 0x51, 0x59, 0xaf, 0xac, 0x36, 0xa2,
	0xb0, 0xb3, 0x55, 0x9d, 0xdd, 0x5d, 0x3f, 0x3f, 0x8c, 0xde, 0x6b, 0x30, 0xa8, 0x68, 0xc6, 0x83,
	0x25, 0x0f, 0x05, 0x8b, 0xa5, 0x36, 0x84, 0x40, 0x33, 0xe5, 0x89, 0xa0, 0xb5, 0x61, 0x6d, 0xdc,
	0x9b, 0xd9, 0x33, 0xa1, 0xd0, 0x29, 0x73, 0x69, 0xdd, 0xe2, 0x2a, 0x24, 0x7b, 0xd0, 0xf5, 0x57,
	0x32, 0x36, 0xcc, 0xcf, 0x69, 0xc3, 0x29, 0x1b, 0x5f, 0xe5, 0x5f, 0x0a, 0x53, 0xda, 0xfc, 0xa6,
	0xee, 0x53, 0x72, 0x08, 0x50, 0x1c, 0xe7, 0x2c, 0x42, 0x6d, 0x68, 0xcb, 0xca, 0x9e, 0x25, 0x37,
	0xa8, 0x0d, 0x39, 0x80, 0xde, 0x1a, 0xd5, 0x52, 0x67, 0x3c, 0x10, 0xb4, 0xed, 0xec, 0x06, 0x8c,
	0x3e, 0xea, 0xf0, 0x7f, 0x6b, 0x28, 0xf2, 0x02, 0x9d, 0x72, 0x0c, 0x3a, 0x19, 0x36, 0xc6, 0x7f,
	0x26, 0x4f, 0xde, 0xaf, 0xd7, 0xe7, 0xfd, 0xb4, 0xa0, 0x59, 0xf5, 0x1d, 0xb2, 0x0f, 0xdd, 0x18,
	0x03, 0x6e, 0x8a, 0xb5, 0x4c, 0x6d, 0x97, 0x9b, 0x98, 0x0c, 0xa0, 0x15, 0x73, 0x5f, 0xc4, 0xf4,
	0xc4, 0x0a, 0x17, 0x90, 0x63, 0xf8, 0x17, 0x60, 0x96, 0x2b, 0x19, 0x46, 0xc6, 0xb6, 0x4d, 0x4f,
	0xad, 0xee, 0x6f, 0xe8, 0x6d, 0x31, 0xcb, 0x11, 0xf4, 0x23, 0xae, 0xe6, 0x65, 0x4b, 0x0b, 0xa4,
	0x67, 0x36, 0xeb, 0x6f, 0x05, 0xab, 0x24, 0x9d, 0x6b, 0x23, 0x12, 0xb6, 0xca, 0x8c, 0x4c, 0x04,
	0x3d, 0x77, 0x49, 0x0e, 0x3e, 0x5a, 0x56, 0xdc, 0x81, 0x4c, 0x42, 0x57, 0xe4, 0xc2, 0xdd, 0x81,
	0x4c, 0xc2, 0xe2, 0x7d, 0xbf, 0x6d, 0x7f, 0xb2, 0xe9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b,
	0x11, 0x26, 0xf3, 0x7f, 0x02, 0x00, 0x00,
}
