/*
Copyright 2019 Cisco Systems

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ospf_sh_topology.proto

package cisco_ios_xr_ipv4_ospf_oper_ospf_processes_process_vrfs_vrf_route_information_route_areas_route_area_multicast_intact_route_areas_multicast_intact_route_area

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OspfShTopology_KEYS struct {
	ProcessName          string   `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	VrfName              string   `protobuf:"bytes,2,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	AreaId               uint32   `protobuf:"varint,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Prefix               string   `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	PrefixLength         uint32   `protobuf:"varint,5,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OspfShTopology_KEYS) Reset()         { *m = OspfShTopology_KEYS{} }
func (m *OspfShTopology_KEYS) String() string { return proto.CompactTextString(m) }
func (*OspfShTopology_KEYS) ProtoMessage()    {}
func (*OspfShTopology_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{0}
}

func (m *OspfShTopology_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShTopology_KEYS.Unmarshal(m, b)
}
func (m *OspfShTopology_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShTopology_KEYS.Marshal(b, m, deterministic)
}
func (m *OspfShTopology_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShTopology_KEYS.Merge(m, src)
}
func (m *OspfShTopology_KEYS) XXX_Size() int {
	return xxx_messageInfo_OspfShTopology_KEYS.Size(m)
}
func (m *OspfShTopology_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShTopology_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShTopology_KEYS proto.InternalMessageInfo

func (m *OspfShTopology_KEYS) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *OspfShTopology_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *OspfShTopology_KEYS) GetAreaId() uint32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *OspfShTopology_KEYS) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *OspfShTopology_KEYS) GetPrefixLength() uint32 {
	if m != nil {
		return m.PrefixLength
	}
	return 0
}

type OspfShTime struct {
	Second               uint32   `protobuf:"varint,1,opt,name=second,proto3" json:"second,omitempty"`
	Nanosecond           uint32   `protobuf:"varint,2,opt,name=nanosecond,proto3" json:"nanosecond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OspfShTime) Reset()         { *m = OspfShTime{} }
func (m *OspfShTime) String() string { return proto.CompactTextString(m) }
func (*OspfShTime) ProtoMessage()    {}
func (*OspfShTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{1}
}

func (m *OspfShTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShTime.Unmarshal(m, b)
}
func (m *OspfShTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShTime.Marshal(b, m, deterministic)
}
func (m *OspfShTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShTime.Merge(m, src)
}
func (m *OspfShTime) XXX_Size() int {
	return xxx_messageInfo_OspfShTime.Size(m)
}
func (m *OspfShTime) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShTime.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShTime proto.InternalMessageInfo

func (m *OspfShTime) GetSecond() uint32 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *OspfShTime) GetNanosecond() uint32 {
	if m != nil {
		return m.Nanosecond
	}
	return 0
}

type OspfShTopCommon struct {
	RouteAreaId               uint32      `protobuf:"varint,1,opt,name=route_area_id,json=routeAreaId,proto3" json:"route_area_id,omitempty"`
	RouteTeMetric             uint32      `protobuf:"varint,2,opt,name=route_te_metric,json=routeTeMetric,proto3" json:"route_te_metric,omitempty"`
	RouteRibVersion           uint32      `protobuf:"varint,3,opt,name=route_rib_version,json=routeRibVersion,proto3" json:"route_rib_version,omitempty"`
	RouteSpfVersion           uint64      `protobuf:"varint,4,opt,name=route_spf_version,json=routeSpfVersion,proto3" json:"route_spf_version,omitempty"`
	RouteForwardDistance      uint32      `protobuf:"varint,5,opt,name=route_forward_distance,json=routeForwardDistance,proto3" json:"route_forward_distance,omitempty"`
	RouteSource               uint32      `protobuf:"varint,6,opt,name=route_source,json=routeSource,proto3" json:"route_source,omitempty"`
	RouteUpdateTime           *OspfShTime `protobuf:"bytes,7,opt,name=route_update_time,json=routeUpdateTime,proto3" json:"route_update_time,omitempty"`
	RouteFailTime             *OspfShTime `protobuf:"bytes,8,opt,name=route_fail_time,json=routeFailTime,proto3" json:"route_fail_time,omitempty"`
	RouteSpfPriority          uint32      `protobuf:"varint,9,opt,name=route_spf_priority,json=routeSpfPriority,proto3" json:"route_spf_priority,omitempty"`
	RouteAutoExcluded         bool        `protobuf:"varint,10,opt,name=route_auto_excluded,json=routeAutoExcluded,proto3" json:"route_auto_excluded,omitempty"`
	RouteSrtePrefixRegistered bool        `protobuf:"varint,11,opt,name=route_srte_prefix_registered,json=routeSrtePrefixRegistered,proto3" json:"route_srte_prefix_registered,omitempty"`
	RouteSrteNbrRegistered    uint32      `protobuf:"varint,12,opt,name=route_srte_nbr_registered,json=routeSrteNbrRegistered,proto3" json:"route_srte_nbr_registered,omitempty"`
	RouteLabelType            uint32      `protobuf:"varint,13,opt,name=route_label_type,json=routeLabelType,proto3" json:"route_label_type,omitempty"`
	RouteLabel                uint32      `protobuf:"varint,14,opt,name=route_label,json=routeLabel,proto3" json:"route_label,omitempty"`
	RouteSspfLabel            uint32      `protobuf:"varint,15,opt,name=route_sspf_label,json=routeSspfLabel,proto3" json:"route_sspf_label,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}    `json:"-"`
	XXX_unrecognized          []byte      `json:"-"`
	XXX_sizecache             int32       `json:"-"`
}

func (m *OspfShTopCommon) Reset()         { *m = OspfShTopCommon{} }
func (m *OspfShTopCommon) String() string { return proto.CompactTextString(m) }
func (*OspfShTopCommon) ProtoMessage()    {}
func (*OspfShTopCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{2}
}

func (m *OspfShTopCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShTopCommon.Unmarshal(m, b)
}
func (m *OspfShTopCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShTopCommon.Marshal(b, m, deterministic)
}
func (m *OspfShTopCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShTopCommon.Merge(m, src)
}
func (m *OspfShTopCommon) XXX_Size() int {
	return xxx_messageInfo_OspfShTopCommon.Size(m)
}
func (m *OspfShTopCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShTopCommon.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShTopCommon proto.InternalMessageInfo

func (m *OspfShTopCommon) GetRouteAreaId() uint32 {
	if m != nil {
		return m.RouteAreaId
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteTeMetric() uint32 {
	if m != nil {
		return m.RouteTeMetric
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteRibVersion() uint32 {
	if m != nil {
		return m.RouteRibVersion
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteSpfVersion() uint64 {
	if m != nil {
		return m.RouteSpfVersion
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteForwardDistance() uint32 {
	if m != nil {
		return m.RouteForwardDistance
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteSource() uint32 {
	if m != nil {
		return m.RouteSource
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteUpdateTime() *OspfShTime {
	if m != nil {
		return m.RouteUpdateTime
	}
	return nil
}

func (m *OspfShTopCommon) GetRouteFailTime() *OspfShTime {
	if m != nil {
		return m.RouteFailTime
	}
	return nil
}

func (m *OspfShTopCommon) GetRouteSpfPriority() uint32 {
	if m != nil {
		return m.RouteSpfPriority
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteAutoExcluded() bool {
	if m != nil {
		return m.RouteAutoExcluded
	}
	return false
}

func (m *OspfShTopCommon) GetRouteSrtePrefixRegistered() bool {
	if m != nil {
		return m.RouteSrtePrefixRegistered
	}
	return false
}

func (m *OspfShTopCommon) GetRouteSrteNbrRegistered() uint32 {
	if m != nil {
		return m.RouteSrteNbrRegistered
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteLabelType() uint32 {
	if m != nil {
		return m.RouteLabelType
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteLabel() uint32 {
	if m != nil {
		return m.RouteLabel
	}
	return 0
}

func (m *OspfShTopCommon) GetRouteSspfLabel() uint32 {
	if m != nil {
		return m.RouteSspfLabel
	}
	return 0
}

type OspfShRepEl struct {
	RepairElementId      string   `protobuf:"bytes,1,opt,name=repair_element_id,json=repairElementId,proto3" json:"repair_element_id,omitempty"`
	RepairLabel          uint32   `protobuf:"varint,2,opt,name=repair_label,json=repairLabel,proto3" json:"repair_label,omitempty"`
	RepairElementType    uint32   `protobuf:"varint,3,opt,name=repair_element_type,json=repairElementType,proto3" json:"repair_element_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OspfShRepEl) Reset()         { *m = OspfShRepEl{} }
func (m *OspfShRepEl) String() string { return proto.CompactTextString(m) }
func (*OspfShRepEl) ProtoMessage()    {}
func (*OspfShRepEl) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{3}
}

func (m *OspfShRepEl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShRepEl.Unmarshal(m, b)
}
func (m *OspfShRepEl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShRepEl.Marshal(b, m, deterministic)
}
func (m *OspfShRepEl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShRepEl.Merge(m, src)
}
func (m *OspfShRepEl) XXX_Size() int {
	return xxx_messageInfo_OspfShRepEl.Size(m)
}
func (m *OspfShRepEl) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShRepEl.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShRepEl proto.InternalMessageInfo

func (m *OspfShRepEl) GetRepairElementId() string {
	if m != nil {
		return m.RepairElementId
	}
	return ""
}

func (m *OspfShRepEl) GetRepairLabel() uint32 {
	if m != nil {
		return m.RepairLabel
	}
	return 0
}

func (m *OspfShRepEl) GetRepairElementType() uint32 {
	if m != nil {
		return m.RepairElementType
	}
	return 0
}

type OspfShSrUloopPath struct {
	MicroloopRepair              []*OspfShRepEl `protobuf:"bytes,1,rep,name=microloop_repair,json=microloopRepair,proto3" json:"microloop_repair,omitempty"`
	MicroloopRepairListSize      uint32         `protobuf:"varint,2,opt,name=microloop_repair_list_size,json=microloopRepairListSize,proto3" json:"microloop_repair_list_size,omitempty"`
	MicroloopTunnelInterfaceName string         `protobuf:"bytes,3,opt,name=microloop_tunnel_interface_name,json=microloopTunnelInterfaceName,proto3" json:"microloop_tunnel_interface_name,omitempty"`
	MicroloopStrictSpf           bool           `protobuf:"varint,4,opt,name=microloop_strict_spf,json=microloopStrictSpf,proto3" json:"microloop_strict_spf,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}       `json:"-"`
	XXX_unrecognized             []byte         `json:"-"`
	XXX_sizecache                int32          `json:"-"`
}

func (m *OspfShSrUloopPath) Reset()         { *m = OspfShSrUloopPath{} }
func (m *OspfShSrUloopPath) String() string { return proto.CompactTextString(m) }
func (*OspfShSrUloopPath) ProtoMessage()    {}
func (*OspfShSrUloopPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{4}
}

func (m *OspfShSrUloopPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShSrUloopPath.Unmarshal(m, b)
}
func (m *OspfShSrUloopPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShSrUloopPath.Marshal(b, m, deterministic)
}
func (m *OspfShSrUloopPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShSrUloopPath.Merge(m, src)
}
func (m *OspfShSrUloopPath) XXX_Size() int {
	return xxx_messageInfo_OspfShSrUloopPath.Size(m)
}
func (m *OspfShSrUloopPath) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShSrUloopPath.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShSrUloopPath proto.InternalMessageInfo

func (m *OspfShSrUloopPath) GetMicroloopRepair() []*OspfShRepEl {
	if m != nil {
		return m.MicroloopRepair
	}
	return nil
}

func (m *OspfShSrUloopPath) GetMicroloopRepairListSize() uint32 {
	if m != nil {
		return m.MicroloopRepairListSize
	}
	return 0
}

func (m *OspfShSrUloopPath) GetMicroloopTunnelInterfaceName() string {
	if m != nil {
		return m.MicroloopTunnelInterfaceName
	}
	return ""
}

func (m *OspfShSrUloopPath) GetMicroloopStrictSpf() bool {
	if m != nil {
		return m.MicroloopStrictSpf
	}
	return false
}

type OspfShNnhInfo struct {
	NeighborNextHopValueType string   `protobuf:"bytes,1,opt,name=neighbor_next_hop_value_type,json=neighborNextHopValueType,proto3" json:"neighbor_next_hop_value_type,omitempty"`
	NeighborNextHopIpAddr    string   `protobuf:"bytes,2,opt,name=neighbor_next_hop_ip_addr,json=neighborNextHopIpAddr,proto3" json:"neighbor_next_hop_ip_addr,omitempty"`
	NeighborNextHopIntfIndex uint32   `protobuf:"varint,3,opt,name=neighbor_next_hop_intf_index,json=neighborNextHopIntfIndex,proto3" json:"neighbor_next_hop_intf_index,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *OspfShNnhInfo) Reset()         { *m = OspfShNnhInfo{} }
func (m *OspfShNnhInfo) String() string { return proto.CompactTextString(m) }
func (*OspfShNnhInfo) ProtoMessage()    {}
func (*OspfShNnhInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{5}
}

func (m *OspfShNnhInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShNnhInfo.Unmarshal(m, b)
}
func (m *OspfShNnhInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShNnhInfo.Marshal(b, m, deterministic)
}
func (m *OspfShNnhInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShNnhInfo.Merge(m, src)
}
func (m *OspfShNnhInfo) XXX_Size() int {
	return xxx_messageInfo_OspfShNnhInfo.Size(m)
}
func (m *OspfShNnhInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShNnhInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShNnhInfo proto.InternalMessageInfo

func (m *OspfShNnhInfo) GetNeighborNextHopValueType() string {
	if m != nil {
		return m.NeighborNextHopValueType
	}
	return ""
}

func (m *OspfShNnhInfo) GetNeighborNextHopIpAddr() string {
	if m != nil {
		return m.NeighborNextHopIpAddr
	}
	return ""
}

func (m *OspfShNnhInfo) GetNeighborNextHopIntfIndex() uint32 {
	if m != nil {
		return m.NeighborNextHopIntfIndex
	}
	return 0
}

type OspfShTopPath struct {
	RouteInterfaceName       string             `protobuf:"bytes,1,opt,name=route_interface_name,json=routeInterfaceName,proto3" json:"route_interface_name,omitempty"`
	RouteInterfaceSnmpIndex  uint32             `protobuf:"varint,2,opt,name=route_interface_snmp_index,json=routeInterfaceSnmpIndex,proto3" json:"route_interface_snmp_index,omitempty"`
	RouteNextHopAddress      string             `protobuf:"bytes,3,opt,name=route_next_hop_address,json=routeNextHopAddress,proto3" json:"route_next_hop_address,omitempty"`
	RouteSource              string             `protobuf:"bytes,4,opt,name=route_source,json=routeSource,proto3" json:"route_source,omitempty"`
	RouteLsaid               string             `protobuf:"bytes,5,opt,name=route_lsaid,json=routeLsaid,proto3" json:"route_lsaid,omitempty"`
	RoutePathIsMcastIntact   bool               `protobuf:"varint,6,opt,name=route_path_is_mcast_intact,json=routePathIsMcastIntact,proto3" json:"route_path_is_mcast_intact,omitempty"`
	RoutePathIsUcmpPath      bool               `protobuf:"varint,7,opt,name=route_path_is_ucmp_path,json=routePathIsUcmpPath,proto3" json:"route_path_is_ucmp_path,omitempty"`
	RouteMetric              uint32             `protobuf:"varint,8,opt,name=route_metric,json=routeMetric,proto3" json:"route_metric,omitempty"`
	LsaType                  uint32             `protobuf:"varint,9,opt,name=lsa_type,json=lsaType,proto3" json:"lsa_type,omitempty"`
	AreaId                   uint32             `protobuf:"varint,10,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	AreaFormat               bool               `protobuf:"varint,11,opt,name=area_format,json=areaFormat,proto3" json:"area_format,omitempty"`
	SrMicroloopAvoidancePath *OspfShSrUloopPath `protobuf:"bytes,12,opt,name=sr_microloop_avoidance_path,json=srMicroloopAvoidancePath,proto3" json:"sr_microloop_avoidance_path,omitempty"`
	RoutePathId              uint32             `protobuf:"varint,13,opt,name=route_path_id,json=routePathId,proto3" json:"route_path_id,omitempty"`
	RoutePathIsRsvpTePath    bool               `protobuf:"varint,14,opt,name=route_path_is_rsvp_te_path,json=routePathIsRsvpTePath,proto3" json:"route_path_is_rsvp_te_path,omitempty"`
	RoutePathIsSrTePath      bool               `protobuf:"varint,15,opt,name=route_path_is_sr_te_path,json=routePathIsSrTePath,proto3" json:"route_path_is_sr_te_path,omitempty"`
	RoutePathIsSrExclPath    bool               `protobuf:"varint,16,opt,name=route_path_is_sr_excl_path,json=routePathIsSrExclPath,proto3" json:"route_path_is_sr_excl_path,omitempty"`
	RoutePathIsSrTeSspfPath  bool               `protobuf:"varint,17,opt,name=route_path_is_sr_te_sspf_path,json=routePathIsSrTeSspfPath,proto3" json:"route_path_is_sr_te_sspf_path,omitempty"`
	NeighborNextHop          []*OspfShNnhInfo   `protobuf:"bytes,18,rep,name=neighbor_next_hop,json=neighborNextHop,proto3" json:"neighbor_next_hop,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}           `json:"-"`
	XXX_unrecognized         []byte             `json:"-"`
	XXX_sizecache            int32              `json:"-"`
}

func (m *OspfShTopPath) Reset()         { *m = OspfShTopPath{} }
func (m *OspfShTopPath) String() string { return proto.CompactTextString(m) }
func (*OspfShTopPath) ProtoMessage()    {}
func (*OspfShTopPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{6}
}

func (m *OspfShTopPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShTopPath.Unmarshal(m, b)
}
func (m *OspfShTopPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShTopPath.Marshal(b, m, deterministic)
}
func (m *OspfShTopPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShTopPath.Merge(m, src)
}
func (m *OspfShTopPath) XXX_Size() int {
	return xxx_messageInfo_OspfShTopPath.Size(m)
}
func (m *OspfShTopPath) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShTopPath.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShTopPath proto.InternalMessageInfo

func (m *OspfShTopPath) GetRouteInterfaceName() string {
	if m != nil {
		return m.RouteInterfaceName
	}
	return ""
}

func (m *OspfShTopPath) GetRouteInterfaceSnmpIndex() uint32 {
	if m != nil {
		return m.RouteInterfaceSnmpIndex
	}
	return 0
}

func (m *OspfShTopPath) GetRouteNextHopAddress() string {
	if m != nil {
		return m.RouteNextHopAddress
	}
	return ""
}

func (m *OspfShTopPath) GetRouteSource() string {
	if m != nil {
		return m.RouteSource
	}
	return ""
}

func (m *OspfShTopPath) GetRouteLsaid() string {
	if m != nil {
		return m.RouteLsaid
	}
	return ""
}

func (m *OspfShTopPath) GetRoutePathIsMcastIntact() bool {
	if m != nil {
		return m.RoutePathIsMcastIntact
	}
	return false
}

func (m *OspfShTopPath) GetRoutePathIsUcmpPath() bool {
	if m != nil {
		return m.RoutePathIsUcmpPath
	}
	return false
}

func (m *OspfShTopPath) GetRouteMetric() uint32 {
	if m != nil {
		return m.RouteMetric
	}
	return 0
}

func (m *OspfShTopPath) GetLsaType() uint32 {
	if m != nil {
		return m.LsaType
	}
	return 0
}

func (m *OspfShTopPath) GetAreaId() uint32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *OspfShTopPath) GetAreaFormat() bool {
	if m != nil {
		return m.AreaFormat
	}
	return false
}

func (m *OspfShTopPath) GetSrMicroloopAvoidancePath() *OspfShSrUloopPath {
	if m != nil {
		return m.SrMicroloopAvoidancePath
	}
	return nil
}

func (m *OspfShTopPath) GetRoutePathId() uint32 {
	if m != nil {
		return m.RoutePathId
	}
	return 0
}

func (m *OspfShTopPath) GetRoutePathIsRsvpTePath() bool {
	if m != nil {
		return m.RoutePathIsRsvpTePath
	}
	return false
}

func (m *OspfShTopPath) GetRoutePathIsSrTePath() bool {
	if m != nil {
		return m.RoutePathIsSrTePath
	}
	return false
}

func (m *OspfShTopPath) GetRoutePathIsSrExclPath() bool {
	if m != nil {
		return m.RoutePathIsSrExclPath
	}
	return false
}

func (m *OspfShTopPath) GetRoutePathIsSrTeSspfPath() bool {
	if m != nil {
		return m.RoutePathIsSrTeSspfPath
	}
	return false
}

func (m *OspfShTopPath) GetNeighborNextHop() []*OspfShNnhInfo {
	if m != nil {
		return m.NeighborNextHop
	}
	return nil
}

type OspfShTopology struct {
	RoutePrefix          string           `protobuf:"bytes,50,opt,name=route_prefix,json=routePrefix,proto3" json:"route_prefix,omitempty"`
	RoutePrefixLength    uint32           `protobuf:"varint,51,opt,name=route_prefix_length,json=routePrefixLength,proto3" json:"route_prefix_length,omitempty"`
	RouteMetric          uint32           `protobuf:"varint,52,opt,name=route_metric,json=routeMetric,proto3" json:"route_metric,omitempty"`
	RouteType            string           `protobuf:"bytes,53,opt,name=route_type,json=routeType,proto3" json:"route_type,omitempty"`
	RouteConnected       bool             `protobuf:"varint,54,opt,name=route_connected,json=routeConnected,proto3" json:"route_connected,omitempty"`
	RouteInfo            *OspfShTopCommon `protobuf:"bytes,55,opt,name=route_info,json=routeInfo,proto3" json:"route_info,omitempty"`
	RoutePath            []*OspfShTopPath `protobuf:"bytes,56,rep,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OspfShTopology) Reset()         { *m = OspfShTopology{} }
func (m *OspfShTopology) String() string { return proto.CompactTextString(m) }
func (*OspfShTopology) ProtoMessage()    {}
func (*OspfShTopology) Descriptor() ([]byte, []int) {
	return fileDescriptor_4169ff6e5af11206, []int{7}
}

func (m *OspfShTopology) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspfShTopology.Unmarshal(m, b)
}
func (m *OspfShTopology) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspfShTopology.Marshal(b, m, deterministic)
}
func (m *OspfShTopology) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspfShTopology.Merge(m, src)
}
func (m *OspfShTopology) XXX_Size() int {
	return xxx_messageInfo_OspfShTopology.Size(m)
}
func (m *OspfShTopology) XXX_DiscardUnknown() {
	xxx_messageInfo_OspfShTopology.DiscardUnknown(m)
}

var xxx_messageInfo_OspfShTopology proto.InternalMessageInfo

func (m *OspfShTopology) GetRoutePrefix() string {
	if m != nil {
		return m.RoutePrefix
	}
	return ""
}

func (m *OspfShTopology) GetRoutePrefixLength() uint32 {
	if m != nil {
		return m.RoutePrefixLength
	}
	return 0
}

func (m *OspfShTopology) GetRouteMetric() uint32 {
	if m != nil {
		return m.RouteMetric
	}
	return 0
}

func (m *OspfShTopology) GetRouteType() string {
	if m != nil {
		return m.RouteType
	}
	return ""
}

func (m *OspfShTopology) GetRouteConnected() bool {
	if m != nil {
		return m.RouteConnected
	}
	return false
}

func (m *OspfShTopology) GetRouteInfo() *OspfShTopCommon {
	if m != nil {
		return m.RouteInfo
	}
	return nil
}

func (m *OspfShTopology) GetRoutePath() []*OspfShTopPath {
	if m != nil {
		return m.RoutePath
	}
	return nil
}

func init() {
	proto.RegisterType((*OspfShTopology_KEYS)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_topology_KEYS")
	proto.RegisterType((*OspfShTime)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_time")
	proto.RegisterType((*OspfShTopCommon)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_top_common")
	proto.RegisterType((*OspfShRepEl)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_rep_el")
	proto.RegisterType((*OspfShSrUloopPath)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_sr_uloop_path")
	proto.RegisterType((*OspfShNnhInfo)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_nnh_info")
	proto.RegisterType((*OspfShTopPath)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_top_path")
	proto.RegisterType((*OspfShTopology)(nil), "cisco_ios_xr_ipv4_ospf_oper.ospf.processes.process.vrfs.vrf.route_information.route_areas.route_area.multicast_intact_route_areas.multicast_intact_route_area.ospf_sh_topology")
}

func init() { proto.RegisterFile("ospf_sh_topology.proto", fileDescriptor_4169ff6e5af11206) }

var fileDescriptor_4169ff6e5af11206 = []byte{
	// 1324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x6f, 0x6b, 0x1c, 0x45,
	0x18, 0x67, 0x9b, 0x9a, 0x5c, 0xe6, 0x92, 0x26, 0x19, 0xdb, 0x64, 0x53, 0x5b, 0x1b, 0x4f, 0xd0,
	0x20, 0x72, 0x94, 0x36, 0xd5, 0x6a, 0xa1, 0x12, 0x34, 0xc1, 0xc3, 0xb6, 0x94, 0xbd, 0xb4, 0xe0,
	0xab, 0x61, 0x6e, 0x77, 0x36, 0x37, 0xb0, 0x3b, 0x33, 0xcc, 0xcc, 0x9d, 0x49, 0xbf, 0x84, 0xe0,
	0x7b, 0x3f, 0x80, 0x14, 0x11, 0xc1, 0x6f, 0xa1, 0x20, 0x82, 0x2f, 0x14, 0xfc, 0x18, 0xe2, 0x6b,
	0x99, 0x67, 0x66, 0x6f, 0x77, 0xef, 0x8a, 0xaf, 0xcd, 0x9b, 0xb0, 0xf7, 0x3c, 0xcf, 0xef, 0x99,
	0xe7, 0xff, 0x33, 0x13, 0xb4, 0x2d, 0x8d, 0xca, 0x89, 0x19, 0x13, 0x2b, 0x95, 0x2c, 0xe4, 0xe9,
	0x79, 0x5f, 0x69, 0x69, 0x25, 0xfe, 0x36, 0x4a, 0xb9, 0x49, 0x25, 0xe1, 0xd2, 0x90, 0x33, 0x4d,
	0xb8, 0x9a, 0x1e, 0x10, 0x10, 0x95, 0x8a, 0xe9, 0xbe, 0xfb, 0x72, 0x82, 0x29, 0x33, 0x86, 0x99,
	0xea, 0xab, 0x3f, 0xd5, 0x39, 0xfc, 0xe9, 0x6b, 0x39, 0xb1, 0x8c, 0x70, 0x91, 0x4b, 0x5d, 0x52,
	0xcb, 0xa5, 0x08, 0x14, 0xaa, 0x19, 0x35, 0x8d, 0xef, 0x7e, 0x39, 0x29, 0x2c, 0x4f, 0xa9, 0xb1,
	0x84, 0x0b, 0x4b, 0x53, 0x4b, 0x9a, 0x72, 0xff, 0xc1, 0xec, 0xbd, 0x8c, 0xd0, 0xb5, 0x79, 0xd3,
	0xc9, 0x17, 0x47, 0x5f, 0x0e, 0xf1, 0x5b, 0x68, 0x2d, 0xd8, 0x43, 0x04, 0x2d, 0x59, 0x1c, 0xed,
	0x45, 0xfb, 0xab, 0x49, 0x37, 0xd0, 0x9e, 0xd0, 0x92, 0xe1, 0x5d, 0xd4, 0x99, 0xea, 0xdc, 0xb3,
	0x2f, 0x01, 0x7b, 0x65, 0xaa, 0x73, 0x60, 0xed, 0xa0, 0x15, 0xa7, 0x9f, 0xf0, 0x2c, 0x5e, 0xda,
	0x8b, 0xf6, 0xd7, 0x93, 0x65, 0xf7, 0x73, 0x90, 0xe1, 0x6d, 0xb4, 0xac, 0x34, 0xcb, 0xf9, 0x59,
	0x7c, 0x19, 0x10, 0xe1, 0x17, 0x7e, 0x1b, 0xad, 0xfb, 0x2f, 0x52, 0x30, 0x71, 0x6a, 0xc7, 0xf1,
	0x6b, 0x00, 0x5b, 0xf3, 0xc4, 0x47, 0x40, 0xeb, 0x1d, 0xa3, 0xb5, 0x99, 0xb1, 0xbc, 0x64, 0x4e,
	0x99, 0x61, 0xa9, 0x14, 0x19, 0x58, 0xb7, 0x9e, 0x84, 0x5f, 0xf8, 0x4d, 0x84, 0x04, 0x15, 0x32,
	0xf0, 0x2e, 0x01, 0xaf, 0x41, 0xe9, 0x7d, 0xd3, 0x41, 0xb8, 0xe1, 0x35, 0x49, 0x65, 0x59, 0x4a,
	0x81, 0x7b, 0x68, 0xbd, 0x0e, 0x8d, 0x33, 0xdd, 0x6b, 0xed, 0x02, 0xf1, 0xd0, 0xdb, 0xff, 0x0e,
	0xda, 0xf0, 0x32, 0x96, 0x91, 0x92, 0x59, 0xcd, 0xd3, 0xa0, 0xdf, 0x43, 0x4f, 0xd8, 0x63, 0x20,
	0xe2, 0xf7, 0xd0, 0x96, 0x97, 0xd3, 0x7c, 0x44, 0xa6, 0x4c, 0x1b, 0x2e, 0x45, 0x08, 0x85, 0x57,
	0x90, 0xf0, 0xd1, 0x73, 0x4f, 0xae, 0x65, 0x9d, 0x49, 0x95, 0xac, 0x0b, 0xcf, 0xe5, 0x20, 0x3b,
	0x54, 0x79, 0x25, 0x7b, 0x80, 0xb6, 0xbd, 0x6c, 0x2e, 0xf5, 0x57, 0x54, 0x67, 0x24, 0xe3, 0xc6,
	0x52, 0x91, 0xb2, 0x10, 0xb0, 0xab, 0xc0, 0x3d, 0xf6, 0xcc, 0xcf, 0x02, 0xcf, 0x25, 0x33, 0x9c,
	0x20, 0x27, 0x3a, 0x65, 0xf1, 0x72, 0xc3, 0xb1, 0x21, 0x90, 0xf0, 0x1f, 0x51, 0x65, 0xc5, 0x44,
	0x65, 0xd4, 0x39, 0xc8, 0x4b, 0x16, 0xaf, 0xec, 0x45, 0xfb, 0xdd, 0x3b, 0x2f, 0xa3, 0xfe, 0xff,
	0xba, 0x8c, 0xfb, 0xcd, 0xaa, 0x08, 0x31, 0x7b, 0x06, 0x5e, 0x9c, 0xb8, 0x32, 0xf9, 0x3d, 0xaa,
	0x92, 0x96, 0x53, 0x5e, 0x78, 0xc7, 0x3a, 0x17, 0xd0, 0x31, 0x5f, 0x62, 0xc7, 0x94, 0x17, 0xe0,
	0xd6, 0xfb, 0x08, 0xd7, 0x65, 0xa3, 0x34, 0x97, 0x9a, 0xdb, 0xf3, 0x78, 0x15, 0x52, 0xbb, 0x59,
	0xd5, 0xcd, 0xd3, 0x40, 0xc7, 0x7d, 0xf4, 0x7a, 0xd0, 0x3b, 0xb1, 0x92, 0xb0, 0xb3, 0xb4, 0x98,
	0x64, 0x2c, 0x8b, 0xd1, 0x5e, 0xb4, 0xdf, 0x49, 0x7c, 0xe6, 0x0f, 0x27, 0x56, 0x1e, 0x05, 0x06,
	0xfe, 0x04, 0xdd, 0x08, 0xda, 0xb5, 0x65, 0x24, 0xf4, 0xa6, 0x66, 0xa7, 0xdc, 0x58, 0xa6, 0x59,
	0x16, 0x77, 0x01, 0xb8, 0xeb, 0xcf, 0xd1, 0x96, 0x3d, 0x05, 0x89, 0x64, 0x26, 0x80, 0x3f, 0x42,
	0xbb, 0x0d, 0x05, 0x62, 0xa4, 0x9b, 0xe8, 0x35, 0xb0, 0x72, 0x7b, 0x86, 0x7e, 0x32, 0xd2, 0x0d,
	0xe8, 0x3e, 0xf2, 0xf6, 0x93, 0x82, 0x8e, 0x58, 0x41, 0xec, 0xb9, 0x62, 0xf1, 0x3a, 0x20, 0xae,
	0x00, 0xfd, 0x91, 0x23, 0x9f, 0x9c, 0x2b, 0x86, 0x6f, 0xa1, 0x6e, 0x43, 0x32, 0xbe, 0xe2, 0x5b,
	0xbd, 0x16, 0xaa, 0x55, 0x19, 0x17, 0x25, 0x2f, 0xb5, 0xd1, 0x50, 0x35, 0x34, 0x2a, 0x07, 0xc9,
	0xde, 0xd7, 0x11, 0xba, 0x52, 0x85, 0x5b, 0x33, 0x45, 0x58, 0x01, 0x8d, 0xc9, 0x14, 0xe5, 0x9a,
	0xb0, 0x82, 0x95, 0x4c, 0xd8, 0x6a, 0x28, 0xac, 0x26, 0x1b, 0x9e, 0x71, 0xe4, 0xe9, 0x83, 0x0c,
	0x5a, 0xcc, 0xcb, 0xfa, 0x43, 0x2e, 0x85, 0x16, 0x03, 0x9a, 0xb7, 0xc5, 0xa5, 0xa0, 0xad, 0x0e,
	0x3c, 0xf3, 0x53, 0x61, 0xab, 0xa5, 0xd0, 0x39, 0xd7, 0xfb, 0x6e, 0xa9, 0x1e, 0xce, 0x46, 0x93,
	0x49, 0x21, 0xa5, 0x22, 0x8a, 0xda, 0x31, 0xfe, 0x33, 0x42, 0x9b, 0x25, 0x4f, 0xb5, 0x04, 0x92,
	0x47, 0xc6, 0xd1, 0xde, 0xd2, 0x7e, 0xf7, 0xce, 0xf7, 0x17, 0xa5, 0xa4, 0x7d, 0x8c, 0x93, 0x8d,
	0x99, 0x1f, 0x09, 0xb8, 0x81, 0x1f, 0xa0, 0xeb, 0xf3, 0xae, 0x91, 0x82, 0x1b, 0x4b, 0x0c, 0x7f,
	0xc1, 0x42, 0x58, 0x77, 0xe6, 0x40, 0x8f, 0xb8, 0xb1, 0x43, 0xfe, 0x82, 0xe1, 0x23, 0x74, 0xab,
	0x06, 0xdb, 0x89, 0x10, 0xac, 0x70, 0x26, 0x30, 0x9d, 0xd3, 0x94, 0xf9, 0x4d, 0xb5, 0x04, 0xf9,
	0xbb, 0x31, 0x13, 0x3b, 0x01, 0xa9, 0x41, 0x25, 0x04, 0xeb, 0xeb, 0x36, 0xba, 0x5a, 0xab, 0x31,
	0x6e, 0xa0, 0x5b, 0xd7, 0x65, 0x30, 0x94, 0x3b, 0x09, 0x9e, 0xf1, 0x86, 0xc0, 0x1a, 0xaa, 0xbc,
	0xf7, 0x4b, 0x84, 0x36, 0x2b, 0xcf, 0x84, 0x18, 0x43, 0x04, 0xf1, 0x43, 0x74, 0x43, 0x30, 0x7e,
	0x3a, 0x1e, 0x49, 0x4d, 0x04, 0x3b, 0xb3, 0x64, 0x2c, 0x15, 0x99, 0xd2, 0x62, 0xc2, 0x7c, 0xe6,
	0x7d, 0x29, 0xc5, 0x95, 0xcc, 0x13, 0x76, 0x66, 0x3f, 0x97, 0xea, 0xb9, 0x13, 0x80, 0xea, 0xbe,
	0x8f, 0x76, 0x17, 0xf1, 0x5c, 0x11, 0x9a, 0x65, 0x3a, 0x6c, 0xdc, 0x6b, 0x73, 0xe0, 0x81, 0x3a,
	0xcc, 0x32, 0xfd, 0xea, 0x93, 0xb9, 0xb0, 0x39, 0xe1, 0x22, 0x63, 0x67, 0xa1, 0xe6, 0xe6, 0x4f,
	0x1e, 0x08, 0x9b, 0x0f, 0x1c, 0xbf, 0xf7, 0xf3, 0x6a, 0xed, 0x8e, 0xad, 0xaa, 0xee, 0x36, 0xba,
	0x5a, 0x95, 0x47, 0x2b, 0xa2, 0xde, 0x0d, 0x3f, 0x8c, 0xda, 0x71, 0x7c, 0x80, 0xae, 0xcf, 0x23,
	0x8c, 0x28, 0x55, 0x30, 0x22, 0xe4, 0xb2, 0x8d, 0x1b, 0x8a, 0x52, 0x81, 0x0d, 0xf8, 0x6e, 0xb5,
	0xea, 0x66, 0x0e, 0x38, 0xbf, 0x99, 0x31, 0x21, 0x85, 0x7e, 0x9e, 0x05, 0xd3, 0x0f, 0x3d, 0x6b,
	0x61, 0xd3, 0xf9, 0x5b, 0x46, 0x6b, 0xd3, 0xd5, 0x33, 0xc3, 0x50, 0x9e, 0xc1, 0xde, 0x5c, 0xad,
	0x66, 0x86, 0xa3, 0xe0, 0x8f, 0x2b, 0xab, 0x9d, 0xd7, 0x84, 0x1b, 0x52, 0x36, 0x4a, 0x19, 0x76,
	0x67, 0x27, 0x8c, 0xae, 0xa7, 0xd4, 0x8e, 0x07, 0xe6, 0xb1, 0x63, 0x0f, 0x80, 0x8b, 0x0f, 0xd0,
	0x4e, 0x1b, 0x3b, 0x49, 0x4b, 0x1f, 0x3e, 0xd8, 0xa5, 0x9d, 0x60, 0xb5, 0x07, 0x3e, 0x4b, 0x4b,
	0xe5, 0xbe, 0x6a, 0xab, 0xc3, 0x95, 0xa2, 0xd3, 0xd8, 0xcf, 0xe1, 0x42, 0xb1, 0x8b, 0x3a, 0x85,
	0xa1, 0xbe, 0x6e, 0xfc, 0x8c, 0x5f, 0x29, 0x0c, 0x85, 0x32, 0x69, 0x5c, 0xb6, 0x50, 0xeb, 0xb2,
	0x75, 0x0b, 0x75, 0x81, 0xe1, 0x9b, 0x39, 0x8c, 0x6c, 0xe4, 0x48, 0xc7, 0x40, 0xc1, 0x7f, 0x47,
	0xe8, 0x0d, 0xa3, 0x49, 0x5d, 0xeb, 0x74, 0x2a, 0x79, 0xe6, 0xae, 0x0c, 0xde, 0xe4, 0x35, 0xd8,
	0x92, 0x3f, 0x5d, 0x94, 0x91, 0xd2, 0x1a, 0x92, 0x49, 0x6c, 0xf4, 0xe3, 0xca, 0xb1, 0xc3, 0xca,
	0x2f, 0x08, 0xf7, 0xec, 0xa2, 0xe7, 0x93, 0x94, 0x85, 0xe5, 0xd2, 0xad, 0x53, 0xe3, 0xd6, 0xd7,
	0x5c, 0x11, 0x68, 0x33, 0x55, 0x24, 0xfc, 0x86, 0x45, 0xd3, 0x49, 0xae, 0x35, 0x72, 0x99, 0x98,
	0xa9, 0x3a, 0xf1, 0xea, 0xef, 0xa1, 0xb8, 0x0d, 0x35, 0x7a, 0x06, 0xdc, 0x58, 0x28, 0x82, 0xa1,
	0x0e, 0xb0, 0x85, 0x13, 0x8d, 0x86, 0x3d, 0xed, 0x81, 0x9b, 0x0b, 0x27, 0x0e, 0xb5, 0x5b, 0xd6,
	0x00, 0x7d, 0x88, 0x6e, 0xbe, 0xea, 0x44, 0xd8, 0x79, 0x80, 0xde, 0x02, 0xf4, 0xce, 0xdc, 0xb1,
	0x6e, 0xf9, 0x01, 0xfe, 0xaf, 0x08, 0x6d, 0x2d, 0xcc, 0x8b, 0x18, 0xc3, 0x42, 0xf9, 0xe1, 0xa2,
	0x64, 0xbf, 0x1a, 0xbb, 0xc9, 0xc6, 0xdc, 0x58, 0xeb, 0xfd, 0x73, 0xb9, 0x35, 0xcd, 0xe0, 0x95,
	0x53, 0xf7, 0x5c, 0x78, 0x8f, 0xdc, 0x69, 0x4c, 0x0a, 0x7f, 0x99, 0xa9, 0xef, 0x4c, 0xed, 0xa7,
	0xc9, 0xdd, 0xb0, 0xb0, 0x6b, 0x49, 0xff, 0x3e, 0x59, 0x68, 0xe3, 0x83, 0xc5, 0x36, 0xbe, 0x89,
	0x50, 0x78, 0x3f, 0xb8, 0x46, 0xbe, 0x07, 0x67, 0xae, 0xfa, 0xa7, 0x83, 0x6b, 0xe5, 0x77, 0xab,
	0x9b, 0x6a, 0x2a, 0x85, 0x60, 0xa9, 0x65, 0x59, 0xfc, 0x01, 0xa4, 0xce, 0xdf, 0x56, 0x3e, 0xad,
	0xa8, 0xf8, 0xb7, 0xa8, 0x52, 0xe4, 0x5c, 0x8e, 0x3f, 0x84, 0x46, 0xfd, 0xf1, 0xc2, 0x5c, 0x67,
	0x67, 0x8f, 0xae, 0xe0, 0xfc, 0xc0, 0xad, 0xcb, 0x5f, 0x67, 0x3e, 0x41, 0xcd, 0xde, 0xbf, 0x58,
	0xe5, 0x57, 0xad, 0xc9, 0xe0, 0x91, 0xeb, 0xab, 0xd1, 0x32, 0xfc, 0x17, 0xe0, 0xee, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x97, 0x1e, 0x0d, 0xfa, 0x1f, 0x10, 0x00, 0x00,
}
