/*
Copyright 2019 Cisco Systems

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pim_gre_hash_bag.proto

package cisco_ios_xr_ipv4_pim_oper_ipv6_pim_standby_vrfs_vrf_gre_gre_hashes_gre_hash

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PimGreHashBag_KEYS struct {
	VrfName              string   `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	SourceAddress        string   `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	DestinationAddress   string   `protobuf:"bytes,3,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	Ifname               string   `protobuf:"bytes,4,opt,name=ifname,proto3" json:"ifname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PimGreHashBag_KEYS) Reset()         { *m = PimGreHashBag_KEYS{} }
func (m *PimGreHashBag_KEYS) String() string { return proto.CompactTextString(m) }
func (*PimGreHashBag_KEYS) ProtoMessage()    {}
func (*PimGreHashBag_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_7705297c4213ce4e, []int{0}
}

func (m *PimGreHashBag_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PimGreHashBag_KEYS.Unmarshal(m, b)
}
func (m *PimGreHashBag_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PimGreHashBag_KEYS.Marshal(b, m, deterministic)
}
func (m *PimGreHashBag_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PimGreHashBag_KEYS.Merge(m, src)
}
func (m *PimGreHashBag_KEYS) XXX_Size() int {
	return xxx_messageInfo_PimGreHashBag_KEYS.Size(m)
}
func (m *PimGreHashBag_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_PimGreHashBag_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_PimGreHashBag_KEYS proto.InternalMessageInfo

func (m *PimGreHashBag_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *PimGreHashBag_KEYS) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *PimGreHashBag_KEYS) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *PimGreHashBag_KEYS) GetIfname() string {
	if m != nil {
		return m.Ifname
	}
	return ""
}

type PimGreHashBag struct {
	NextHopInterface     string   `protobuf:"bytes,50,opt,name=next_hop_interface,json=nextHopInterface,proto3" json:"next_hop_interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PimGreHashBag) Reset()         { *m = PimGreHashBag{} }
func (m *PimGreHashBag) String() string { return proto.CompactTextString(m) }
func (*PimGreHashBag) ProtoMessage()    {}
func (*PimGreHashBag) Descriptor() ([]byte, []int) {
	return fileDescriptor_7705297c4213ce4e, []int{1}
}

func (m *PimGreHashBag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PimGreHashBag.Unmarshal(m, b)
}
func (m *PimGreHashBag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PimGreHashBag.Marshal(b, m, deterministic)
}
func (m *PimGreHashBag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PimGreHashBag.Merge(m, src)
}
func (m *PimGreHashBag) XXX_Size() int {
	return xxx_messageInfo_PimGreHashBag.Size(m)
}
func (m *PimGreHashBag) XXX_DiscardUnknown() {
	xxx_messageInfo_PimGreHashBag.DiscardUnknown(m)
}

var xxx_messageInfo_PimGreHashBag proto.InternalMessageInfo

func (m *PimGreHashBag) GetNextHopInterface() string {
	if m != nil {
		return m.NextHopInterface
	}
	return ""
}

func init() {
	proto.RegisterType((*PimGreHashBag_KEYS)(nil), "cisco_ios_xr_ipv4_pim_oper.ipv6_pim.standby.vrfs.vrf.gre.gre_hashes.gre_hash.pim_gre_hash_bag_KEYS")
	proto.RegisterType((*PimGreHashBag)(nil), "cisco_ios_xr_ipv4_pim_oper.ipv6_pim.standby.vrfs.vrf.gre.gre_hashes.gre_hash.pim_gre_hash_bag")
}

func init() { proto.RegisterFile("pim_gre_hash_bag.proto", fileDescriptor_7705297c4213ce4e) }

var fileDescriptor_7705297c4213ce4e = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0xca, 0xaa, 0x01, 0x65, 0x89, 0xb8, 0xd4, 0x9b, 0x2c, 0x08, 0x1e, 0x24, 0x82,
	0x8a, 0x67, 0x3d, 0x08, 0x8a, 0xe2, 0x41, 0x4f, 0x9e, 0x86, 0xb4, 0x9d, 0xb4, 0x39, 0x34, 0x09,
	0x33, 0x31, 0xac, 0x7f, 0xc7, 0x5f, 0x2a, 0xcd, 0xda, 0x65, 0xe9, 0x25, 0x64, 0xde, 0xfb, 0x5e,
	0x5e, 0x18, 0xb1, 0x08, 0xb6, 0x87, 0x96, 0x10, 0x3a, 0xcd, 0x1d, 0x54, 0xba, 0x55, 0x81, 0x7c,
	0xf4, 0xf2, 0xad, 0xb6, 0x5c, 0x7b, 0xb0, 0x9e, 0x61, 0x45, 0x60, 0x43, 0xba, 0x83, 0x81, 0xf4,
	0x01, 0x49, 0xd9, 0x90, 0xee, 0x87, 0x49, 0x71, 0xd4, 0xae, 0xa9, 0x7e, 0x54, 0x22, 0xc3, 0xc3,
	0xa1, 0x5a, 0x42, 0x35, 0x3e, 0x86, 0xbc, 0xb9, 0x2e, 0x7f, 0x0b, 0x71, 0x3a, 0x2d, 0x82, 0xd7,
	0xa7, 0xaf, 0x4f, 0x79, 0x26, 0x0e, 0x12, 0x19, 0x70, 0xba, 0xc7, 0xb2, 0x38, 0x2f, 0x2e, 0x0f,
	0x3f, 0xf6, 0x13, 0x99, 0x77, 0xdd, 0xa3, 0xbc, 0x10, 0xc7, 0xec, 0xbf, 0xa9, 0x46, 0xd0, 0x4d,
	0x43, 0xc8, 0x5c, 0xee, 0x64, 0xe0, 0x68, 0xad, 0x3e, 0xae, 0x45, 0x79, 0x2d, 0x4e, 0x1a, 0xe4,
	0x68, 0x9d, 0x8e, 0xd6, 0xbb, 0x0d, 0xbb, 0x9b, 0x59, 0xb9, 0x65, 0x8d, 0x81, 0x85, 0x98, 0x59,
	0x93, 0x0b, 0xf7, 0x32, 0xf3, 0x3f, 0x2d, 0x1f, 0xc4, 0x7c, 0xfa, 0x47, 0x79, 0x25, 0xa4, 0xc3,
	0x55, 0x84, 0xce, 0x07, 0xb0, 0x2e, 0x22, 0x19, 0x5d, 0x63, 0x79, 0x93, 0x73, 0xf3, 0xc1, 0x79,
	0xf6, 0xe1, 0x65, 0xd4, 0xab, 0x59, 0xde, 0xdd, 0xed, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15,
	0x42, 0xa1, 0x2e, 0x55, 0x01, 0x00, 0x00,
}
