/*
Copyright 2019 Cisco Systems

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pim_mroute_bag.proto

package cisco_ios_xr_ipv4_pim_oper_pim_active_vrfs_vrf_mib_databases_mib_database

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PimMrouteBag_KEYS struct {
	VrfName              string   `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	SourceAddress        string   `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	GroupAddress         string   `protobuf:"bytes,3,opt,name=group_address,json=groupAddress,proto3" json:"group_address,omitempty"`
	SourceNetmask        uint32   `protobuf:"varint,4,opt,name=source_netmask,json=sourceNetmask,proto3" json:"source_netmask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PimMrouteBag_KEYS) Reset()         { *m = PimMrouteBag_KEYS{} }
func (m *PimMrouteBag_KEYS) String() string { return proto.CompactTextString(m) }
func (*PimMrouteBag_KEYS) ProtoMessage()    {}
func (*PimMrouteBag_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8098ca7299bdc29, []int{0}
}

func (m *PimMrouteBag_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PimMrouteBag_KEYS.Unmarshal(m, b)
}
func (m *PimMrouteBag_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PimMrouteBag_KEYS.Marshal(b, m, deterministic)
}
func (m *PimMrouteBag_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PimMrouteBag_KEYS.Merge(m, src)
}
func (m *PimMrouteBag_KEYS) XXX_Size() int {
	return xxx_messageInfo_PimMrouteBag_KEYS.Size(m)
}
func (m *PimMrouteBag_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_PimMrouteBag_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_PimMrouteBag_KEYS proto.InternalMessageInfo

func (m *PimMrouteBag_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *PimMrouteBag_KEYS) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *PimMrouteBag_KEYS) GetGroupAddress() string {
	if m != nil {
		return m.GroupAddress
	}
	return ""
}

func (m *PimMrouteBag_KEYS) GetSourceNetmask() uint32 {
	if m != nil {
		return m.SourceNetmask
	}
	return 0
}

type PimAddrtype struct {
	AfName               string   `protobuf:"bytes,1,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`
	Ipv4Address          string   `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address          string   `protobuf:"bytes,3,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PimAddrtype) Reset()         { *m = PimAddrtype{} }
func (m *PimAddrtype) String() string { return proto.CompactTextString(m) }
func (*PimAddrtype) ProtoMessage()    {}
func (*PimAddrtype) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8098ca7299bdc29, []int{1}
}

func (m *PimAddrtype) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PimAddrtype.Unmarshal(m, b)
}
func (m *PimAddrtype) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PimAddrtype.Marshal(b, m, deterministic)
}
func (m *PimAddrtype) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PimAddrtype.Merge(m, src)
}
func (m *PimAddrtype) XXX_Size() int {
	return xxx_messageInfo_PimAddrtype.Size(m)
}
func (m *PimAddrtype) XXX_DiscardUnknown() {
	xxx_messageInfo_PimAddrtype.DiscardUnknown(m)
}

var xxx_messageInfo_PimAddrtype proto.InternalMessageInfo

func (m *PimAddrtype) GetAfName() string {
	if m != nil {
		return m.AfName
	}
	return ""
}

func (m *PimAddrtype) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *PimAddrtype) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

type PimMrouteBag struct {
	SourceAddressXr        *PimAddrtype `protobuf:"bytes,50,opt,name=source_address_xr,json=sourceAddressXr,proto3" json:"source_address_xr,omitempty"`
	GroupAddressXr         *PimAddrtype `protobuf:"bytes,51,opt,name=group_address_xr,json=groupAddressXr,proto3" json:"group_address_xr,omitempty"`
	UpstreamAssertTimer    int32        `protobuf:"zigzag32,52,opt,name=upstream_assert_timer,json=upstreamAssertTimer,proto3" json:"upstream_assert_timer,omitempty"`
	AssertMetric           uint32       `protobuf:"varint,53,opt,name=assert_metric,json=assertMetric,proto3" json:"assert_metric,omitempty"`
	AssertMetricPreference uint32       `protobuf:"varint,54,opt,name=assert_metric_preference,json=assertMetricPreference,proto3" json:"assert_metric_preference,omitempty"`
	AssertRptBit           bool         `protobuf:"varint,55,opt,name=assert_rpt_bit,json=assertRptBit,proto3" json:"assert_rpt_bit,omitempty"`
	SptBit                 bool         `protobuf:"varint,56,opt,name=spt_bit,json=sptBit,proto3" json:"spt_bit,omitempty"`
	RpfNeighbor            *PimAddrtype `protobuf:"bytes,57,opt,name=rpf_neighbor,json=rpfNeighbor,proto3" json:"rpf_neighbor,omitempty"`
	RpfRoot                *PimAddrtype `protobuf:"bytes,58,opt,name=rpf_root,json=rpfRoot,proto3" json:"rpf_root,omitempty"`
	RpfMask                uint32       `protobuf:"varint,59,opt,name=rpf_mask,json=rpfMask,proto3" json:"rpf_mask,omitempty"`
	RpfSafi                uint32       `protobuf:"varint,60,opt,name=rpf_safi,json=rpfSafi,proto3" json:"rpf_safi,omitempty"`
	RpfTableName           string       `protobuf:"bytes,61,opt,name=rpf_table_name,json=rpfTableName,proto3" json:"rpf_table_name,omitempty"`
	RpfDrop                bool         `protobuf:"varint,62,opt,name=rpf_drop,json=rpfDrop,proto3" json:"rpf_drop,omitempty"`
	RpfExtranet            bool         `protobuf:"varint,63,opt,name=rpf_extranet,json=rpfExtranet,proto3" json:"rpf_extranet,omitempty"`
	RpfInterfaceName       string       `protobuf:"bytes,64,opt,name=rpf_interface_name,json=rpfInterfaceName,proto3" json:"rpf_interface_name,omitempty"`
	RpfVrfName             string       `protobuf:"bytes,65,opt,name=rpf_vrf_name,json=rpfVrfName,proto3" json:"rpf_vrf_name,omitempty"`
	BidirectionalRoute     bool         `protobuf:"varint,66,opt,name=bidirectional_route,json=bidirectionalRoute,proto3" json:"bidirectional_route,omitempty"`
	Uptime                 uint64       `protobuf:"varint,67,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Protocol               string       `protobuf:"bytes,68,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}     `json:"-"`
	XXX_unrecognized       []byte       `json:"-"`
	XXX_sizecache          int32        `json:"-"`
}

func (m *PimMrouteBag) Reset()         { *m = PimMrouteBag{} }
func (m *PimMrouteBag) String() string { return proto.CompactTextString(m) }
func (*PimMrouteBag) ProtoMessage()    {}
func (*PimMrouteBag) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8098ca7299bdc29, []int{2}
}

func (m *PimMrouteBag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PimMrouteBag.Unmarshal(m, b)
}
func (m *PimMrouteBag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PimMrouteBag.Marshal(b, m, deterministic)
}
func (m *PimMrouteBag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PimMrouteBag.Merge(m, src)
}
func (m *PimMrouteBag) XXX_Size() int {
	return xxx_messageInfo_PimMrouteBag.Size(m)
}
func (m *PimMrouteBag) XXX_DiscardUnknown() {
	xxx_messageInfo_PimMrouteBag.DiscardUnknown(m)
}

var xxx_messageInfo_PimMrouteBag proto.InternalMessageInfo

func (m *PimMrouteBag) GetSourceAddressXr() *PimAddrtype {
	if m != nil {
		return m.SourceAddressXr
	}
	return nil
}

func (m *PimMrouteBag) GetGroupAddressXr() *PimAddrtype {
	if m != nil {
		return m.GroupAddressXr
	}
	return nil
}

func (m *PimMrouteBag) GetUpstreamAssertTimer() int32 {
	if m != nil {
		return m.UpstreamAssertTimer
	}
	return 0
}

func (m *PimMrouteBag) GetAssertMetric() uint32 {
	if m != nil {
		return m.AssertMetric
	}
	return 0
}

func (m *PimMrouteBag) GetAssertMetricPreference() uint32 {
	if m != nil {
		return m.AssertMetricPreference
	}
	return 0
}

func (m *PimMrouteBag) GetAssertRptBit() bool {
	if m != nil {
		return m.AssertRptBit
	}
	return false
}

func (m *PimMrouteBag) GetSptBit() bool {
	if m != nil {
		return m.SptBit
	}
	return false
}

func (m *PimMrouteBag) GetRpfNeighbor() *PimAddrtype {
	if m != nil {
		return m.RpfNeighbor
	}
	return nil
}

func (m *PimMrouteBag) GetRpfRoot() *PimAddrtype {
	if m != nil {
		return m.RpfRoot
	}
	return nil
}

func (m *PimMrouteBag) GetRpfMask() uint32 {
	if m != nil {
		return m.RpfMask
	}
	return 0
}

func (m *PimMrouteBag) GetRpfSafi() uint32 {
	if m != nil {
		return m.RpfSafi
	}
	return 0
}

func (m *PimMrouteBag) GetRpfTableName() string {
	if m != nil {
		return m.RpfTableName
	}
	return ""
}

func (m *PimMrouteBag) GetRpfDrop() bool {
	if m != nil {
		return m.RpfDrop
	}
	return false
}

func (m *PimMrouteBag) GetRpfExtranet() bool {
	if m != nil {
		return m.RpfExtranet
	}
	return false
}

func (m *PimMrouteBag) GetRpfInterfaceName() string {
	if m != nil {
		return m.RpfInterfaceName
	}
	return ""
}

func (m *PimMrouteBag) GetRpfVrfName() string {
	if m != nil {
		return m.RpfVrfName
	}
	return ""
}

func (m *PimMrouteBag) GetBidirectionalRoute() bool {
	if m != nil {
		return m.BidirectionalRoute
	}
	return false
}

func (m *PimMrouteBag) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *PimMrouteBag) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func init() {
	proto.RegisterType((*PimMrouteBag_KEYS)(nil), "cisco_ios_xr_ipv4_pim_oper.pim.active.vrfs.vrf.mib_databases.mib_database.pim_mroute_bag_KEYS")
	proto.RegisterType((*PimAddrtype)(nil), "cisco_ios_xr_ipv4_pim_oper.pim.active.vrfs.vrf.mib_databases.mib_database.pim_addrtype")
	proto.RegisterType((*PimMrouteBag)(nil), "cisco_ios_xr_ipv4_pim_oper.pim.active.vrfs.vrf.mib_databases.mib_database.pim_mroute_bag")
}

func init() { proto.RegisterFile("pim_mroute_bag.proto", fileDescriptor_f8098ca7299bdc29) }

var fileDescriptor_f8098ca7299bdc29 = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x4f, 0x14, 0x31,
	0x14, 0xce, 0x28, 0x59, 0xd6, 0xb2, 0xac, 0x50, 0x14, 0xab, 0xa7, 0x11, 0x35, 0x99, 0x83, 0x19,
	0x13, 0x40, 0xc4, 0xdf, 0x82, 0x70, 0x20, 0x06, 0x62, 0x06, 0xa2, 0x78, 0x6a, 0x3a, 0xb3, 0x2d,
	0x36, 0x30, 0xd3, 0xe6, 0xb5, 0xbb, 0x41, 0x6f, 0xc6, 0x3f, 0xc5, 0xa3, 0xff, 0xa4, 0x79, 0x9d,
	0x99, 0x95, 0xf1, 0xec, 0x5e, 0x36, 0xdb, 0xef, 0xfb, 0xe6, 0x7d, 0xaf, 0x5f, 0xfb, 0x4a, 0x6e,
	0x59, 0x5d, 0xf2, 0x12, 0xcc, 0xd8, 0x4b, 0x9e, 0x8b, 0xb3, 0xd4, 0x82, 0xf1, 0x86, 0x1e, 0x14,
	0xda, 0x15, 0x86, 0x6b, 0xe3, 0xf8, 0x25, 0x70, 0x6d, 0x27, 0x9b, 0x1c, 0x75, 0xc6, 0x4a, 0x48,
	0xad, 0x2e, 0x53, 0x51, 0x78, 0x3d, 0x91, 0xe9, 0x04, 0x94, 0xc3, 0x9f, 0xb4, 0xd4, 0x39, 0x1f,
	0x09, 0x2f, 0x72, 0xe1, 0xa4, 0xeb, 0xac, 0xd6, 0x7e, 0x45, 0x64, 0xa5, 0xeb, 0xc1, 0x3f, 0xec,
	0x7f, 0x39, 0xa6, 0x77, 0x49, 0x7f, 0x02, 0x8a, 0x57, 0xa2, 0x94, 0x2c, 0x8a, 0xa3, 0xe4, 0x46,
	0x36, 0x3f, 0x01, 0x75, 0x24, 0x4a, 0x49, 0x1f, 0x91, 0xa1, 0x33, 0x63, 0x28, 0x24, 0x17, 0xa3,
	0x11, 0x48, 0xe7, 0xd8, 0xb5, 0x20, 0x58, 0xac, 0xd1, 0x9d, 0x1a, 0xa4, 0x0f, 0xc8, 0xe2, 0x19,
	0x98, 0xb1, 0x9d, 0xaa, 0xae, 0x07, 0xd5, 0x20, 0x80, 0xad, 0xe8, 0x6f, 0xad, 0x4a, 0xfa, 0x52,
	0xb8, 0x73, 0x36, 0x17, 0x47, 0xc9, 0x62, 0x5b, 0xeb, 0xa8, 0x06, 0xd7, 0x4a, 0x32, 0xc0, 0x26,
	0xb1, 0x92, 0xff, 0x66, 0x25, 0xbd, 0x43, 0xe6, 0x45, 0xa7, 0xb9, 0x9e, 0xa8, 0x7b, 0xbb, 0x4f,
	0x06, 0x21, 0x8e, 0x6e, 0x67, 0x0b, 0x88, 0xb5, 0x96, 0xb5, 0x64, 0xeb, 0x9f, 0xb6, 0x50, 0xb2,
	0xd5, 0x48, 0xd6, 0x7e, 0xf7, 0xc9, 0xb0, 0x1b, 0x0a, 0xfd, 0x19, 0x91, 0xe5, 0xee, 0xae, 0xf9,
	0x25, 0xb0, 0xf5, 0x38, 0x4a, 0x16, 0xd6, 0x3f, 0xa7, 0xff, 0xed, 0x3c, 0xd2, 0xab, 0xdb, 0xcc,
	0x6e, 0x76, 0x12, 0x3d, 0x05, 0xfa, 0x23, 0x22, 0x4b, 0x9d, 0x50, 0xb1, 0x89, 0x8d, 0xd9, 0x36,
	0x31, 0xbc, 0x7a, 0x60, 0xa7, 0x40, 0xd7, 0xc9, 0xed, 0xb1, 0x75, 0x1e, 0xa4, 0x28, 0xb9, 0x70,
	0x4e, 0x82, 0xe7, 0x5e, 0x97, 0x12, 0xd8, 0x66, 0x1c, 0x25, 0xcb, 0xd9, 0x4a, 0x4b, 0xee, 0x04,
	0xee, 0x04, 0x29, 0xbc, 0x0b, 0x8d, 0xb4, 0x94, 0x1e, 0x74, 0xc1, 0x9e, 0x86, 0x53, 0x1e, 0xd4,
	0xe0, 0x61, 0xc0, 0xe8, 0x36, 0x61, 0x1d, 0x11, 0xb7, 0x20, 0x95, 0x04, 0x59, 0x15, 0x92, 0x6d,
	0x05, 0xfd, 0xea, 0x55, 0xfd, 0xc7, 0x29, 0x4b, 0x1f, 0x92, 0x61, 0xf3, 0x25, 0x58, 0xcf, 0x73,
	0xed, 0xd9, 0xb3, 0x38, 0x4a, 0xfa, 0x6d, 0xfd, 0xcc, 0xfa, 0x5d, 0xed, 0xf1, 0xd2, 0xb8, 0x86,
	0xde, 0x0e, 0x74, 0xcf, 0xd5, 0xc4, 0x77, 0x32, 0x00, 0xab, 0x78, 0x25, 0xf5, 0xd9, 0xd7, 0xdc,
	0x00, 0x7b, 0x3e, 0xdb, 0x40, 0x17, 0xc0, 0xaa, 0xa3, 0xc6, 0x8b, 0x02, 0xe9, 0xa3, 0x37, 0x18,
	0xe3, 0xd9, 0x8b, 0xd9, 0xfa, 0xce, 0x83, 0x55, 0x99, 0x31, 0x1e, 0x67, 0x1b, 0x3d, 0xc3, 0xb8,
	0xbd, 0x0c, 0xc1, 0x22, 0x75, 0x28, 0xdc, 0x79, 0x4b, 0x39, 0xa1, 0x34, 0x7b, 0x35, 0xa5, 0x8e,
	0x85, 0xd2, 0x18, 0x32, 0x52, 0x5e, 0xe4, 0x17, 0xb2, 0x1e, 0xbd, 0xd7, 0xf5, 0x40, 0x83, 0x55,
	0x27, 0x08, 0x86, 0x01, 0x6c, 0x0a, 0x8c, 0xc0, 0x58, 0xf6, 0x26, 0xa4, 0x8c, 0x05, 0xf6, 0xc0,
	0x58, 0x1c, 0x3c, 0xa4, 0xe4, 0xa5, 0x07, 0x51, 0x49, 0xcf, 0xde, 0x06, 0x1a, 0xd3, 0xd8, 0x6f,
	0x20, 0xfa, 0x98, 0x50, 0x94, 0xe8, 0xca, 0x4b, 0x50, 0xa2, 0x68, 0x7c, 0xde, 0x05, 0x9f, 0x25,
	0xb0, 0xea, 0xa0, 0x25, 0x82, 0x57, 0x5c, 0x17, 0x9c, 0xbe, 0x53, 0x3b, 0x41, 0x47, 0xc0, 0xaa,
	0x4f, 0xcd, 0x53, 0xf5, 0x84, 0xac, 0xe4, 0x7a, 0xa4, 0x41, 0x16, 0x5e, 0x9b, 0x4a, 0x5c, 0xf0,
	0x30, 0xd0, 0x6c, 0x37, 0x38, 0xd3, 0x0e, 0x95, 0x21, 0x43, 0x57, 0x49, 0x6f, 0x6c, 0xf1, 0x3a,
	0xb3, 0xf7, 0x71, 0x94, 0xcc, 0x65, 0xcd, 0x8a, 0xde, 0x23, 0xfd, 0xf0, 0xf4, 0x16, 0xe6, 0x82,
	0xed, 0x05, 0x9b, 0xe9, 0x3a, 0xef, 0x85, 0x7f, 0x1b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e,
	0x1a, 0x35, 0xc1, 0xac, 0x05, 0x00, 0x00,
}
