/*
Copyright 2019 Cisco Systems

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qos_stats.proto

package cisco_ios_xr_qos_ma_oper_qos_nv_interface_table_interface_nodes_node_output_service_policy_names_service_policy_instance_statistics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QosStats_KEYS struct {
	InterfaceName        string   `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	NodeName             string   `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ServicePolicyName    string   `protobuf:"bytes,3,opt,name=service_policy_name,json=servicePolicyName,proto3" json:"service_policy_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QosStats_KEYS) Reset()         { *m = QosStats_KEYS{} }
func (m *QosStats_KEYS) String() string { return proto.CompactTextString(m) }
func (*QosStats_KEYS) ProtoMessage()    {}
func (*QosStats_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{0}
}

func (m *QosStats_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QosStats_KEYS.Unmarshal(m, b)
}
func (m *QosStats_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QosStats_KEYS.Marshal(b, m, deterministic)
}
func (m *QosStats_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QosStats_KEYS.Merge(m, src)
}
func (m *QosStats_KEYS) XXX_Size() int {
	return xxx_messageInfo_QosStats_KEYS.Size(m)
}
func (m *QosStats_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_QosStats_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_QosStats_KEYS proto.InternalMessageInfo

func (m *QosStats_KEYS) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *QosStats_KEYS) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *QosStats_KEYS) GetServicePolicyName() string {
	if m != nil {
		return m.ServicePolicyName
	}
	return ""
}

type GenStatsSt struct {
	TransmitPackets         uint64   `protobuf:"varint,1,opt,name=transmit_packets,json=transmitPackets,proto3" json:"transmit_packets,omitempty"`
	TransmitBytes           uint64   `protobuf:"varint,2,opt,name=transmit_bytes,json=transmitBytes,proto3" json:"transmit_bytes,omitempty"`
	TotalDropPackets        uint64   `protobuf:"varint,3,opt,name=total_drop_packets,json=totalDropPackets,proto3" json:"total_drop_packets,omitempty"`
	TotalDropBytes          uint64   `protobuf:"varint,4,opt,name=total_drop_bytes,json=totalDropBytes,proto3" json:"total_drop_bytes,omitempty"`
	TotalDropRate           uint32   `protobuf:"varint,5,opt,name=total_drop_rate,json=totalDropRate,proto3" json:"total_drop_rate,omitempty"`
	MatchDataRate           uint32   `protobuf:"varint,6,opt,name=match_data_rate,json=matchDataRate,proto3" json:"match_data_rate,omitempty"`
	TotalTransmitRate       uint32   `protobuf:"varint,7,opt,name=total_transmit_rate,json=totalTransmitRate,proto3" json:"total_transmit_rate,omitempty"`
	PrePolicyMatchedPackets uint64   `protobuf:"varint,8,opt,name=pre_policy_matched_packets,json=prePolicyMatchedPackets,proto3" json:"pre_policy_matched_packets,omitempty"`
	PrePolicyMatchedBytes   uint64   `protobuf:"varint,9,opt,name=pre_policy_matched_bytes,json=prePolicyMatchedBytes,proto3" json:"pre_policy_matched_bytes,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *GenStatsSt) Reset()         { *m = GenStatsSt{} }
func (m *GenStatsSt) String() string { return proto.CompactTextString(m) }
func (*GenStatsSt) ProtoMessage()    {}
func (*GenStatsSt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{1}
}

func (m *GenStatsSt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenStatsSt.Unmarshal(m, b)
}
func (m *GenStatsSt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenStatsSt.Marshal(b, m, deterministic)
}
func (m *GenStatsSt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenStatsSt.Merge(m, src)
}
func (m *GenStatsSt) XXX_Size() int {
	return xxx_messageInfo_GenStatsSt.Size(m)
}
func (m *GenStatsSt) XXX_DiscardUnknown() {
	xxx_messageInfo_GenStatsSt.DiscardUnknown(m)
}

var xxx_messageInfo_GenStatsSt proto.InternalMessageInfo

func (m *GenStatsSt) GetTransmitPackets() uint64 {
	if m != nil {
		return m.TransmitPackets
	}
	return 0
}

func (m *GenStatsSt) GetTransmitBytes() uint64 {
	if m != nil {
		return m.TransmitBytes
	}
	return 0
}

func (m *GenStatsSt) GetTotalDropPackets() uint64 {
	if m != nil {
		return m.TotalDropPackets
	}
	return 0
}

func (m *GenStatsSt) GetTotalDropBytes() uint64 {
	if m != nil {
		return m.TotalDropBytes
	}
	return 0
}

func (m *GenStatsSt) GetTotalDropRate() uint32 {
	if m != nil {
		return m.TotalDropRate
	}
	return 0
}

func (m *GenStatsSt) GetMatchDataRate() uint32 {
	if m != nil {
		return m.MatchDataRate
	}
	return 0
}

func (m *GenStatsSt) GetTotalTransmitRate() uint32 {
	if m != nil {
		return m.TotalTransmitRate
	}
	return 0
}

func (m *GenStatsSt) GetPrePolicyMatchedPackets() uint64 {
	if m != nil {
		return m.PrePolicyMatchedPackets
	}
	return 0
}

func (m *GenStatsSt) GetPrePolicyMatchedBytes() uint64 {
	if m != nil {
		return m.PrePolicyMatchedBytes
	}
	return 0
}

type PolicyParamUint32St_ struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit                 string   `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyParamUint32St_) Reset()         { *m = PolicyParamUint32St_{} }
func (m *PolicyParamUint32St_) String() string { return proto.CompactTextString(m) }
func (*PolicyParamUint32St_) ProtoMessage()    {}
func (*PolicyParamUint32St_) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{2}
}

func (m *PolicyParamUint32St_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyParamUint32St_.Unmarshal(m, b)
}
func (m *PolicyParamUint32St_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyParamUint32St_.Marshal(b, m, deterministic)
}
func (m *PolicyParamUint32St_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyParamUint32St_.Merge(m, src)
}
func (m *PolicyParamUint32St_) XXX_Size() int {
	return xxx_messageInfo_PolicyParamUint32St_.Size(m)
}
func (m *PolicyParamUint32St_) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyParamUint32St_.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyParamUint32St_ proto.InternalMessageInfo

func (m *PolicyParamUint32St_) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PolicyParamUint32St_) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type QStatsSt struct {
	QueueId                uint32                  `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	TailDropPackets        uint64                  `protobuf:"varint,2,opt,name=tail_drop_packets,json=tailDropPackets,proto3" json:"tail_drop_packets,omitempty"`
	TailDropBytes          uint64                  `protobuf:"varint,3,opt,name=tail_drop_bytes,json=tailDropBytes,proto3" json:"tail_drop_bytes,omitempty"`
	AtmClp0DropPackets     uint64                  `protobuf:"varint,4,opt,name=atm_clp0_drop_packets,json=atmClp0DropPackets,proto3" json:"atm_clp0_drop_packets,omitempty"`
	AtmClp0DropBytes       uint64                  `protobuf:"varint,5,opt,name=atm_clp0_drop_bytes,json=atmClp0DropBytes,proto3" json:"atm_clp0_drop_bytes,omitempty"`
	AtmClp1DropPackets     uint64                  `protobuf:"varint,6,opt,name=atm_clp1_drop_packets,json=atmClp1DropPackets,proto3" json:"atm_clp1_drop_packets,omitempty"`
	AtmClp1DropBytes       uint64                  `protobuf:"varint,7,opt,name=atm_clp1_drop_bytes,json=atmClp1DropBytes,proto3" json:"atm_clp1_drop_bytes,omitempty"`
	QueueInstanceLength    []*PolicyParamUint32St_ `protobuf:"bytes,8,rep,name=queue_instance_length,json=queueInstanceLength,proto3" json:"queue_instance_length,omitempty"`
	QueueAverageLength     []*PolicyParamUint32St_ `protobuf:"bytes,9,rep,name=queue_average_length,json=queueAverageLength,proto3" json:"queue_average_length,omitempty"`
	QueueMaxLength         []*PolicyParamUint32St_ `protobuf:"bytes,10,rep,name=queue_max_length,json=queueMaxLength,proto3" json:"queue_max_length,omitempty"`
	QueueDropThreshold     uint32                  `protobuf:"varint,11,opt,name=queue_drop_threshold,json=queueDropThreshold,proto3" json:"queue_drop_threshold,omitempty"`
	ForcedWredStatsDisplay bool                    `protobuf:"varint,12,opt,name=forced_wred_stats_display,json=forcedWredStatsDisplay,proto3" json:"forced_wred_stats_display,omitempty"`
	RandomDropPackets      uint64                  `protobuf:"varint,13,opt,name=random_drop_packets,json=randomDropPackets,proto3" json:"random_drop_packets,omitempty"`
	RandomDropBytes        uint64                  `protobuf:"varint,14,opt,name=random_drop_bytes,json=randomDropBytes,proto3" json:"random_drop_bytes,omitempty"`
	MaxThresholdPackets    uint64                  `protobuf:"varint,15,opt,name=max_threshold_packets,json=maxThresholdPackets,proto3" json:"max_threshold_packets,omitempty"`
	MaxThresholdBytes      uint64                  `protobuf:"varint,16,opt,name=max_threshold_bytes,json=maxThresholdBytes,proto3" json:"max_threshold_bytes,omitempty"`
	ConformPackets         uint64                  `protobuf:"varint,17,opt,name=conform_packets,json=conformPackets,proto3" json:"conform_packets,omitempty"`
	ConformBytes           uint64                  `protobuf:"varint,18,opt,name=conform_bytes,json=conformBytes,proto3" json:"conform_bytes,omitempty"`
	ExceedPackets          uint64                  `protobuf:"varint,19,opt,name=exceed_packets,json=exceedPackets,proto3" json:"exceed_packets,omitempty"`
	ExceedBytes            uint64                  `protobuf:"varint,20,opt,name=exceed_bytes,json=exceedBytes,proto3" json:"exceed_bytes,omitempty"`
	ConformRate            uint32                  `protobuf:"varint,21,opt,name=conform_rate,json=conformRate,proto3" json:"conform_rate,omitempty"`
	ExceedRate             uint32                  `protobuf:"varint,22,opt,name=exceed_rate,json=exceedRate,proto3" json:"exceed_rate,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *QStatsSt) Reset()         { *m = QStatsSt{} }
func (m *QStatsSt) String() string { return proto.CompactTextString(m) }
func (*QStatsSt) ProtoMessage()    {}
func (*QStatsSt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{3}
}

func (m *QStatsSt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QStatsSt.Unmarshal(m, b)
}
func (m *QStatsSt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QStatsSt.Marshal(b, m, deterministic)
}
func (m *QStatsSt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QStatsSt.Merge(m, src)
}
func (m *QStatsSt) XXX_Size() int {
	return xxx_messageInfo_QStatsSt.Size(m)
}
func (m *QStatsSt) XXX_DiscardUnknown() {
	xxx_messageInfo_QStatsSt.DiscardUnknown(m)
}

var xxx_messageInfo_QStatsSt proto.InternalMessageInfo

func (m *QStatsSt) GetQueueId() uint32 {
	if m != nil {
		return m.QueueId
	}
	return 0
}

func (m *QStatsSt) GetTailDropPackets() uint64 {
	if m != nil {
		return m.TailDropPackets
	}
	return 0
}

func (m *QStatsSt) GetTailDropBytes() uint64 {
	if m != nil {
		return m.TailDropBytes
	}
	return 0
}

func (m *QStatsSt) GetAtmClp0DropPackets() uint64 {
	if m != nil {
		return m.AtmClp0DropPackets
	}
	return 0
}

func (m *QStatsSt) GetAtmClp0DropBytes() uint64 {
	if m != nil {
		return m.AtmClp0DropBytes
	}
	return 0
}

func (m *QStatsSt) GetAtmClp1DropPackets() uint64 {
	if m != nil {
		return m.AtmClp1DropPackets
	}
	return 0
}

func (m *QStatsSt) GetAtmClp1DropBytes() uint64 {
	if m != nil {
		return m.AtmClp1DropBytes
	}
	return 0
}

func (m *QStatsSt) GetQueueInstanceLength() []*PolicyParamUint32St_ {
	if m != nil {
		return m.QueueInstanceLength
	}
	return nil
}

func (m *QStatsSt) GetQueueAverageLength() []*PolicyParamUint32St_ {
	if m != nil {
		return m.QueueAverageLength
	}
	return nil
}

func (m *QStatsSt) GetQueueMaxLength() []*PolicyParamUint32St_ {
	if m != nil {
		return m.QueueMaxLength
	}
	return nil
}

func (m *QStatsSt) GetQueueDropThreshold() uint32 {
	if m != nil {
		return m.QueueDropThreshold
	}
	return 0
}

func (m *QStatsSt) GetForcedWredStatsDisplay() bool {
	if m != nil {
		return m.ForcedWredStatsDisplay
	}
	return false
}

func (m *QStatsSt) GetRandomDropPackets() uint64 {
	if m != nil {
		return m.RandomDropPackets
	}
	return 0
}

func (m *QStatsSt) GetRandomDropBytes() uint64 {
	if m != nil {
		return m.RandomDropBytes
	}
	return 0
}

func (m *QStatsSt) GetMaxThresholdPackets() uint64 {
	if m != nil {
		return m.MaxThresholdPackets
	}
	return 0
}

func (m *QStatsSt) GetMaxThresholdBytes() uint64 {
	if m != nil {
		return m.MaxThresholdBytes
	}
	return 0
}

func (m *QStatsSt) GetConformPackets() uint64 {
	if m != nil {
		return m.ConformPackets
	}
	return 0
}

func (m *QStatsSt) GetConformBytes() uint64 {
	if m != nil {
		return m.ConformBytes
	}
	return 0
}

func (m *QStatsSt) GetExceedPackets() uint64 {
	if m != nil {
		return m.ExceedPackets
	}
	return 0
}

func (m *QStatsSt) GetExceedBytes() uint64 {
	if m != nil {
		return m.ExceedBytes
	}
	return 0
}

func (m *QStatsSt) GetConformRate() uint32 {
	if m != nil {
		return m.ConformRate
	}
	return 0
}

func (m *QStatsSt) GetExceedRate() uint32 {
	if m != nil {
		return m.ExceedRate
	}
	return 0
}

type PlcColorClassStatsSt struct {
	ConformClassConformPackets uint64   `protobuf:"varint,1,opt,name=conform_class_conform_packets,json=conformClassConformPackets,proto3" json:"conform_class_conform_packets,omitempty"`
	ConformClassConformBytes   uint64   `protobuf:"varint,2,opt,name=conform_class_conform_bytes,json=conformClassConformBytes,proto3" json:"conform_class_conform_bytes,omitempty"`
	ConformClassConformRate    uint32   `protobuf:"varint,3,opt,name=conform_class_conform_rate,json=conformClassConformRate,proto3" json:"conform_class_conform_rate,omitempty"`
	ConformClassExceedPackets  uint64   `protobuf:"varint,4,opt,name=conform_class_exceed_packets,json=conformClassExceedPackets,proto3" json:"conform_class_exceed_packets,omitempty"`
	ConformClassExceedBytes    uint64   `protobuf:"varint,5,opt,name=conform_class_exceed_bytes,json=conformClassExceedBytes,proto3" json:"conform_class_exceed_bytes,omitempty"`
	ConformClassExceedRate     uint32   `protobuf:"varint,6,opt,name=conform_class_exceed_rate,json=conformClassExceedRate,proto3" json:"conform_class_exceed_rate,omitempty"`
	ConformClassViolatePackets uint64   `protobuf:"varint,7,opt,name=conform_class_violate_packets,json=conformClassViolatePackets,proto3" json:"conform_class_violate_packets,omitempty"`
	ConformClassViolateBytes   uint64   `protobuf:"varint,8,opt,name=conform_class_violate_bytes,json=conformClassViolateBytes,proto3" json:"conform_class_violate_bytes,omitempty"`
	ConformClassViolateRate    uint32   `protobuf:"varint,9,opt,name=conform_class_violate_rate,json=conformClassViolateRate,proto3" json:"conform_class_violate_rate,omitempty"`
	ExceedClassExceedPackets   uint64   `protobuf:"varint,10,opt,name=exceed_class_exceed_packets,json=exceedClassExceedPackets,proto3" json:"exceed_class_exceed_packets,omitempty"`
	ExceedClassExceedBytes     uint64   `protobuf:"varint,11,opt,name=exceed_class_exceed_bytes,json=exceedClassExceedBytes,proto3" json:"exceed_class_exceed_bytes,omitempty"`
	ExceedClassExceedRate      uint32   `protobuf:"varint,12,opt,name=exceed_class_exceed_rate,json=exceedClassExceedRate,proto3" json:"exceed_class_exceed_rate,omitempty"`
	ExceedClassViolatePackets  uint64   `protobuf:"varint,13,opt,name=exceed_class_violate_packets,json=exceedClassViolatePackets,proto3" json:"exceed_class_violate_packets,omitempty"`
	ExceedClassViolateBytes    uint64   `protobuf:"varint,14,opt,name=exceed_class_violate_bytes,json=exceedClassViolateBytes,proto3" json:"exceed_class_violate_bytes,omitempty"`
	ExceedClassViolateRate     uint32   `protobuf:"varint,15,opt,name=exceed_class_violate_rate,json=exceedClassViolateRate,proto3" json:"exceed_class_violate_rate,omitempty"`
	ViolateClassViolatePackets uint64   `protobuf:"varint,16,opt,name=violate_class_violate_packets,json=violateClassViolatePackets,proto3" json:"violate_class_violate_packets,omitempty"`
	ViolateClassViolateBytes   uint64   `protobuf:"varint,17,opt,name=violate_class_violate_bytes,json=violateClassViolateBytes,proto3" json:"violate_class_violate_bytes,omitempty"`
	ViolateClassViolateRate    uint32   `protobuf:"varint,18,opt,name=violate_class_violate_rate,json=violateClassViolateRate,proto3" json:"violate_class_violate_rate,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *PlcColorClassStatsSt) Reset()         { *m = PlcColorClassStatsSt{} }
func (m *PlcColorClassStatsSt) String() string { return proto.CompactTextString(m) }
func (*PlcColorClassStatsSt) ProtoMessage()    {}
func (*PlcColorClassStatsSt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{4}
}

func (m *PlcColorClassStatsSt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlcColorClassStatsSt.Unmarshal(m, b)
}
func (m *PlcColorClassStatsSt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlcColorClassStatsSt.Marshal(b, m, deterministic)
}
func (m *PlcColorClassStatsSt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlcColorClassStatsSt.Merge(m, src)
}
func (m *PlcColorClassStatsSt) XXX_Size() int {
	return xxx_messageInfo_PlcColorClassStatsSt.Size(m)
}
func (m *PlcColorClassStatsSt) XXX_DiscardUnknown() {
	xxx_messageInfo_PlcColorClassStatsSt.DiscardUnknown(m)
}

var xxx_messageInfo_PlcColorClassStatsSt proto.InternalMessageInfo

func (m *PlcColorClassStatsSt) GetConformClassConformPackets() uint64 {
	if m != nil {
		return m.ConformClassConformPackets
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassConformBytes() uint64 {
	if m != nil {
		return m.ConformClassConformBytes
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassConformRate() uint32 {
	if m != nil {
		return m.ConformClassConformRate
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassExceedPackets() uint64 {
	if m != nil {
		return m.ConformClassExceedPackets
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassExceedBytes() uint64 {
	if m != nil {
		return m.ConformClassExceedBytes
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassExceedRate() uint32 {
	if m != nil {
		return m.ConformClassExceedRate
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassViolatePackets() uint64 {
	if m != nil {
		return m.ConformClassViolatePackets
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassViolateBytes() uint64 {
	if m != nil {
		return m.ConformClassViolateBytes
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetConformClassViolateRate() uint32 {
	if m != nil {
		return m.ConformClassViolateRate
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetExceedClassExceedPackets() uint64 {
	if m != nil {
		return m.ExceedClassExceedPackets
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetExceedClassExceedBytes() uint64 {
	if m != nil {
		return m.ExceedClassExceedBytes
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetExceedClassExceedRate() uint32 {
	if m != nil {
		return m.ExceedClassExceedRate
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetExceedClassViolatePackets() uint64 {
	if m != nil {
		return m.ExceedClassViolatePackets
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetExceedClassViolateBytes() uint64 {
	if m != nil {
		return m.ExceedClassViolateBytes
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetExceedClassViolateRate() uint32 {
	if m != nil {
		return m.ExceedClassViolateRate
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetViolateClassViolatePackets() uint64 {
	if m != nil {
		return m.ViolateClassViolatePackets
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetViolateClassViolateBytes() uint64 {
	if m != nil {
		return m.ViolateClassViolateBytes
	}
	return 0
}

func (m *PlcColorClassStatsSt) GetViolateClassViolateRate() uint32 {
	if m != nil {
		return m.ViolateClassViolateRate
	}
	return 0
}

type PlcStatsSt struct {
	DropPackets          uint64                `protobuf:"varint,1,opt,name=drop_packets,json=dropPackets,proto3" json:"drop_packets,omitempty"`
	DropBytes            uint64                `protobuf:"varint,2,opt,name=drop_bytes,json=dropBytes,proto3" json:"drop_bytes,omitempty"`
	ConformPackets       uint64                `protobuf:"varint,3,opt,name=conform_packets,json=conformPackets,proto3" json:"conform_packets,omitempty"`
	ConformBytes         uint64                `protobuf:"varint,4,opt,name=conform_bytes,json=conformBytes,proto3" json:"conform_bytes,omitempty"`
	ExceedPackets        uint64                `protobuf:"varint,5,opt,name=exceed_packets,json=exceedPackets,proto3" json:"exceed_packets,omitempty"`
	ExceedBytes          uint64                `protobuf:"varint,6,opt,name=exceed_bytes,json=exceedBytes,proto3" json:"exceed_bytes,omitempty"`
	ViolatePackets       uint64                `protobuf:"varint,7,opt,name=violate_packets,json=violatePackets,proto3" json:"violate_packets,omitempty"`
	ViolateBytes         uint64                `protobuf:"varint,8,opt,name=violate_bytes,json=violateBytes,proto3" json:"violate_bytes,omitempty"`
	ParentDropPackets    uint64                `protobuf:"varint,9,opt,name=parent_drop_packets,json=parentDropPackets,proto3" json:"parent_drop_packets,omitempty"`
	ParentDropBytes      uint64                `protobuf:"varint,10,opt,name=parent_drop_bytes,json=parentDropBytes,proto3" json:"parent_drop_bytes,omitempty"`
	ConformRate          uint32                `protobuf:"varint,11,opt,name=conform_rate,json=conformRate,proto3" json:"conform_rate,omitempty"`
	ExceedRate           uint32                `protobuf:"varint,12,opt,name=exceed_rate,json=exceedRate,proto3" json:"exceed_rate,omitempty"`
	ViolateRate          uint32                `protobuf:"varint,13,opt,name=violate_rate,json=violateRate,proto3" json:"violate_rate,omitempty"`
	ColorClassStats      *PlcColorClassStatsSt `protobuf:"bytes,14,opt,name=color_class_stats,json=colorClassStats,proto3" json:"color_class_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PlcStatsSt) Reset()         { *m = PlcStatsSt{} }
func (m *PlcStatsSt) String() string { return proto.CompactTextString(m) }
func (*PlcStatsSt) ProtoMessage()    {}
func (*PlcStatsSt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{5}
}

func (m *PlcStatsSt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlcStatsSt.Unmarshal(m, b)
}
func (m *PlcStatsSt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlcStatsSt.Marshal(b, m, deterministic)
}
func (m *PlcStatsSt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlcStatsSt.Merge(m, src)
}
func (m *PlcStatsSt) XXX_Size() int {
	return xxx_messageInfo_PlcStatsSt.Size(m)
}
func (m *PlcStatsSt) XXX_DiscardUnknown() {
	xxx_messageInfo_PlcStatsSt.DiscardUnknown(m)
}

var xxx_messageInfo_PlcStatsSt proto.InternalMessageInfo

func (m *PlcStatsSt) GetDropPackets() uint64 {
	if m != nil {
		return m.DropPackets
	}
	return 0
}

func (m *PlcStatsSt) GetDropBytes() uint64 {
	if m != nil {
		return m.DropBytes
	}
	return 0
}

func (m *PlcStatsSt) GetConformPackets() uint64 {
	if m != nil {
		return m.ConformPackets
	}
	return 0
}

func (m *PlcStatsSt) GetConformBytes() uint64 {
	if m != nil {
		return m.ConformBytes
	}
	return 0
}

func (m *PlcStatsSt) GetExceedPackets() uint64 {
	if m != nil {
		return m.ExceedPackets
	}
	return 0
}

func (m *PlcStatsSt) GetExceedBytes() uint64 {
	if m != nil {
		return m.ExceedBytes
	}
	return 0
}

func (m *PlcStatsSt) GetViolatePackets() uint64 {
	if m != nil {
		return m.ViolatePackets
	}
	return 0
}

func (m *PlcStatsSt) GetViolateBytes() uint64 {
	if m != nil {
		return m.ViolateBytes
	}
	return 0
}

func (m *PlcStatsSt) GetParentDropPackets() uint64 {
	if m != nil {
		return m.ParentDropPackets
	}
	return 0
}

func (m *PlcStatsSt) GetParentDropBytes() uint64 {
	if m != nil {
		return m.ParentDropBytes
	}
	return 0
}

func (m *PlcStatsSt) GetConformRate() uint32 {
	if m != nil {
		return m.ConformRate
	}
	return 0
}

func (m *PlcStatsSt) GetExceedRate() uint32 {
	if m != nil {
		return m.ExceedRate
	}
	return 0
}

func (m *PlcStatsSt) GetViolateRate() uint32 {
	if m != nil {
		return m.ViolateRate
	}
	return 0
}

func (m *PlcStatsSt) GetColorClassStats() *PlcColorClassStatsSt {
	if m != nil {
		return m.ColorClassStats
	}
	return nil
}

type WredTypeValue struct {
	WredType             string   `protobuf:"bytes,1,opt,name=wred_type,json=wredType,proto3" json:"wred_type,omitempty"`
	Value                uint32   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WredTypeValue) Reset()         { *m = WredTypeValue{} }
func (m *WredTypeValue) String() string { return proto.CompactTextString(m) }
func (*WredTypeValue) ProtoMessage()    {}
func (*WredTypeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{6}
}

func (m *WredTypeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WredTypeValue.Unmarshal(m, b)
}
func (m *WredTypeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WredTypeValue.Marshal(b, m, deterministic)
}
func (m *WredTypeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WredTypeValue.Merge(m, src)
}
func (m *WredTypeValue) XXX_Size() int {
	return xxx_messageInfo_WredTypeValue.Size(m)
}
func (m *WredTypeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_WredTypeValue.DiscardUnknown(m)
}

var xxx_messageInfo_WredTypeValue proto.InternalMessageInfo

func (m *WredTypeValue) GetWredType() string {
	if m != nil {
		return m.WredType
	}
	return ""
}

func (m *WredTypeValue) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type RedProfileStats struct {
	ProfileTitle         string           `protobuf:"bytes,1,opt,name=profile_title,json=profileTitle,proto3" json:"profile_title,omitempty"`
	RedLabel             []*WredTypeValue `protobuf:"bytes,2,rep,name=red_label,json=redLabel,proto3" json:"red_label,omitempty"`
	RedTransmitPackets   uint64           `protobuf:"varint,3,opt,name=red_transmit_packets,json=redTransmitPackets,proto3" json:"red_transmit_packets,omitempty"`
	RedTransmitBytes     uint64           `protobuf:"varint,4,opt,name=red_transmit_bytes,json=redTransmitBytes,proto3" json:"red_transmit_bytes,omitempty"`
	RandomDropPackets    uint64           `protobuf:"varint,5,opt,name=random_drop_packets,json=randomDropPackets,proto3" json:"random_drop_packets,omitempty"`
	RandomDropBytes      uint64           `protobuf:"varint,6,opt,name=random_drop_bytes,json=randomDropBytes,proto3" json:"random_drop_bytes,omitempty"`
	MaxThresholdPackets  uint64           `protobuf:"varint,7,opt,name=max_threshold_packets,json=maxThresholdPackets,proto3" json:"max_threshold_packets,omitempty"`
	MaxThresholdBytes    uint64           `protobuf:"varint,8,opt,name=max_threshold_bytes,json=maxThresholdBytes,proto3" json:"max_threshold_bytes,omitempty"`
	RedEcnMarkedPackets  uint64           `protobuf:"varint,9,opt,name=red_ecn_marked_packets,json=redEcnMarkedPackets,proto3" json:"red_ecn_marked_packets,omitempty"`
	RedEcnMarkedBytes    uint64           `protobuf:"varint,10,opt,name=red_ecn_marked_bytes,json=redEcnMarkedBytes,proto3" json:"red_ecn_marked_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RedProfileStats) Reset()         { *m = RedProfileStats{} }
func (m *RedProfileStats) String() string { return proto.CompactTextString(m) }
func (*RedProfileStats) ProtoMessage()    {}
func (*RedProfileStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{7}
}

func (m *RedProfileStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedProfileStats.Unmarshal(m, b)
}
func (m *RedProfileStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedProfileStats.Marshal(b, m, deterministic)
}
func (m *RedProfileStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedProfileStats.Merge(m, src)
}
func (m *RedProfileStats) XXX_Size() int {
	return xxx_messageInfo_RedProfileStats.Size(m)
}
func (m *RedProfileStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RedProfileStats.DiscardUnknown(m)
}

var xxx_messageInfo_RedProfileStats proto.InternalMessageInfo

func (m *RedProfileStats) GetProfileTitle() string {
	if m != nil {
		return m.ProfileTitle
	}
	return ""
}

func (m *RedProfileStats) GetRedLabel() []*WredTypeValue {
	if m != nil {
		return m.RedLabel
	}
	return nil
}

func (m *RedProfileStats) GetRedTransmitPackets() uint64 {
	if m != nil {
		return m.RedTransmitPackets
	}
	return 0
}

func (m *RedProfileStats) GetRedTransmitBytes() uint64 {
	if m != nil {
		return m.RedTransmitBytes
	}
	return 0
}

func (m *RedProfileStats) GetRandomDropPackets() uint64 {
	if m != nil {
		return m.RandomDropPackets
	}
	return 0
}

func (m *RedProfileStats) GetRandomDropBytes() uint64 {
	if m != nil {
		return m.RandomDropBytes
	}
	return 0
}

func (m *RedProfileStats) GetMaxThresholdPackets() uint64 {
	if m != nil {
		return m.MaxThresholdPackets
	}
	return 0
}

func (m *RedProfileStats) GetMaxThresholdBytes() uint64 {
	if m != nil {
		return m.MaxThresholdBytes
	}
	return 0
}

func (m *RedProfileStats) GetRedEcnMarkedPackets() uint64 {
	if m != nil {
		return m.RedEcnMarkedPackets
	}
	return 0
}

func (m *RedProfileStats) GetRedEcnMarkedBytes() uint64 {
	if m != nil {
		return m.RedEcnMarkedBytes
	}
	return 0
}

type IphcStatsSt struct {
	NonTcpTotalOutPackets      uint64   `protobuf:"varint,1,opt,name=non_tcp_total_out_packets,json=nonTcpTotalOutPackets,proto3" json:"non_tcp_total_out_packets,omitempty"`
	NonTcpTotalOutBytes        uint64   `protobuf:"varint,2,opt,name=non_tcp_total_out_bytes,json=nonTcpTotalOutBytes,proto3" json:"non_tcp_total_out_bytes,omitempty"`
	NonTcpBytesSaved           uint64   `protobuf:"varint,3,opt,name=non_tcp_bytes_saved,json=nonTcpBytesSaved,proto3" json:"non_tcp_bytes_saved,omitempty"`
	NonTcpCompressedPacketsOut uint64   `protobuf:"varint,4,opt,name=non_tcp_compressed_packets_out,json=nonTcpCompressedPacketsOut,proto3" json:"non_tcp_compressed_packets_out,omitempty"`
	NonTcpBytesSentRate        uint32   `protobuf:"varint,5,opt,name=non_tcp_bytes_sent_rate,json=nonTcpBytesSentRate,proto3" json:"non_tcp_bytes_sent_rate,omitempty"`
	NonTcpFullHeaderPacketsOut uint64   `protobuf:"varint,6,opt,name=non_tcp_full_header_packets_out,json=nonTcpFullHeaderPacketsOut,proto3" json:"non_tcp_full_header_packets_out,omitempty"`
	TcpTotalOutPackets         uint64   `protobuf:"varint,7,opt,name=tcp_total_out_packets,json=tcpTotalOutPackets,proto3" json:"tcp_total_out_packets,omitempty"`
	TcpTotalOutBytes           uint64   `protobuf:"varint,8,opt,name=tcp_total_out_bytes,json=tcpTotalOutBytes,proto3" json:"tcp_total_out_bytes,omitempty"`
	TcpBytesSaved              uint64   `protobuf:"varint,9,opt,name=tcp_bytes_saved,json=tcpBytesSaved,proto3" json:"tcp_bytes_saved,omitempty"`
	TcpCompressedPacketsOut    uint64   `protobuf:"varint,10,opt,name=tcp_compressed_packets_out,json=tcpCompressedPacketsOut,proto3" json:"tcp_compressed_packets_out,omitempty"`
	TcpBytesSentRate           uint32   `protobuf:"varint,11,opt,name=tcp_bytes_sent_rate,json=tcpBytesSentRate,proto3" json:"tcp_bytes_sent_rate,omitempty"`
	TcpFullHeaderPacketsOut    uint64   `protobuf:"varint,12,opt,name=tcp_full_header_packets_out,json=tcpFullHeaderPacketsOut,proto3" json:"tcp_full_header_packets_out,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *IphcStatsSt) Reset()         { *m = IphcStatsSt{} }
func (m *IphcStatsSt) String() string { return proto.CompactTextString(m) }
func (*IphcStatsSt) ProtoMessage()    {}
func (*IphcStatsSt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{8}
}

func (m *IphcStatsSt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IphcStatsSt.Unmarshal(m, b)
}
func (m *IphcStatsSt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IphcStatsSt.Marshal(b, m, deterministic)
}
func (m *IphcStatsSt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IphcStatsSt.Merge(m, src)
}
func (m *IphcStatsSt) XXX_Size() int {
	return xxx_messageInfo_IphcStatsSt.Size(m)
}
func (m *IphcStatsSt) XXX_DiscardUnknown() {
	xxx_messageInfo_IphcStatsSt.DiscardUnknown(m)
}

var xxx_messageInfo_IphcStatsSt proto.InternalMessageInfo

func (m *IphcStatsSt) GetNonTcpTotalOutPackets() uint64 {
	if m != nil {
		return m.NonTcpTotalOutPackets
	}
	return 0
}

func (m *IphcStatsSt) GetNonTcpTotalOutBytes() uint64 {
	if m != nil {
		return m.NonTcpTotalOutBytes
	}
	return 0
}

func (m *IphcStatsSt) GetNonTcpBytesSaved() uint64 {
	if m != nil {
		return m.NonTcpBytesSaved
	}
	return 0
}

func (m *IphcStatsSt) GetNonTcpCompressedPacketsOut() uint64 {
	if m != nil {
		return m.NonTcpCompressedPacketsOut
	}
	return 0
}

func (m *IphcStatsSt) GetNonTcpBytesSentRate() uint32 {
	if m != nil {
		return m.NonTcpBytesSentRate
	}
	return 0
}

func (m *IphcStatsSt) GetNonTcpFullHeaderPacketsOut() uint64 {
	if m != nil {
		return m.NonTcpFullHeaderPacketsOut
	}
	return 0
}

func (m *IphcStatsSt) GetTcpTotalOutPackets() uint64 {
	if m != nil {
		return m.TcpTotalOutPackets
	}
	return 0
}

func (m *IphcStatsSt) GetTcpTotalOutBytes() uint64 {
	if m != nil {
		return m.TcpTotalOutBytes
	}
	return 0
}

func (m *IphcStatsSt) GetTcpBytesSaved() uint64 {
	if m != nil {
		return m.TcpBytesSaved
	}
	return 0
}

func (m *IphcStatsSt) GetTcpCompressedPacketsOut() uint64 {
	if m != nil {
		return m.TcpCompressedPacketsOut
	}
	return 0
}

func (m *IphcStatsSt) GetTcpBytesSentRate() uint32 {
	if m != nil {
		return m.TcpBytesSentRate
	}
	return 0
}

func (m *IphcStatsSt) GetTcpFullHeaderPacketsOut() uint64 {
	if m != nil {
		return m.TcpFullHeaderPacketsOut
	}
	return 0
}

type CacStatsSt struct {
	DropPackets          uint64   `protobuf:"varint,1,opt,name=drop_packets,json=dropPackets,proto3" json:"drop_packets,omitempty"`
	DropBytes            uint64   `protobuf:"varint,2,opt,name=drop_bytes,json=dropBytes,proto3" json:"drop_bytes,omitempty"`
	DropRates            uint32   `protobuf:"varint,3,opt,name=drop_rates,json=dropRates,proto3" json:"drop_rates,omitempty"`
	Admitpackets         uint64   `protobuf:"varint,4,opt,name=admitpackets,proto3" json:"admitpackets,omitempty"`
	AdmitBytes           uint64   `protobuf:"varint,5,opt,name=admit_bytes,json=admitBytes,proto3" json:"admit_bytes,omitempty"`
	AdmitRates           uint32   `protobuf:"varint,6,opt,name=admit_rates,json=admitRates,proto3" json:"admit_rates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacStatsSt) Reset()         { *m = CacStatsSt{} }
func (m *CacStatsSt) String() string { return proto.CompactTextString(m) }
func (*CacStatsSt) ProtoMessage()    {}
func (*CacStatsSt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{9}
}

func (m *CacStatsSt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacStatsSt.Unmarshal(m, b)
}
func (m *CacStatsSt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacStatsSt.Marshal(b, m, deterministic)
}
func (m *CacStatsSt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacStatsSt.Merge(m, src)
}
func (m *CacStatsSt) XXX_Size() int {
	return xxx_messageInfo_CacStatsSt.Size(m)
}
func (m *CacStatsSt) XXX_DiscardUnknown() {
	xxx_messageInfo_CacStatsSt.DiscardUnknown(m)
}

var xxx_messageInfo_CacStatsSt proto.InternalMessageInfo

func (m *CacStatsSt) GetDropPackets() uint64 {
	if m != nil {
		return m.DropPackets
	}
	return 0
}

func (m *CacStatsSt) GetDropBytes() uint64 {
	if m != nil {
		return m.DropBytes
	}
	return 0
}

func (m *CacStatsSt) GetDropRates() uint32 {
	if m != nil {
		return m.DropRates
	}
	return 0
}

func (m *CacStatsSt) GetAdmitpackets() uint64 {
	if m != nil {
		return m.Admitpackets
	}
	return 0
}

func (m *CacStatsSt) GetAdmitBytes() uint64 {
	if m != nil {
		return m.AdmitBytes
	}
	return 0
}

func (m *CacStatsSt) GetAdmitRates() uint32 {
	if m != nil {
		return m.AdmitRates
	}
	return 0
}

type ClassStats struct {
	CounterValidityBitmask uint64             `protobuf:"varint,1,opt,name=counter_validity_bitmask,json=counterValidityBitmask,proto3" json:"counter_validity_bitmask,omitempty"`
	ClassName              string             `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	SharedQueueId          uint32             `protobuf:"varint,3,opt,name=shared_queue_id,json=sharedQueueId,proto3" json:"shared_queue_id,omitempty"`
	QueueDescr             string             `protobuf:"bytes,4,opt,name=queue_descr,json=queueDescr,proto3" json:"queue_descr,omitempty"`
	CacState               string             `protobuf:"bytes,5,opt,name=cac_state,json=cacState,proto3" json:"cac_state,omitempty"`
	GeneralStats           *GenStatsSt        `protobuf:"bytes,6,opt,name=general_stats,json=generalStats,proto3" json:"general_stats,omitempty"`
	QueueStatsArray        []*QStatsSt        `protobuf:"bytes,7,rep,name=queue_stats_array,json=queueStatsArray,proto3" json:"queue_stats_array,omitempty"`
	PoliceStatsArray       []*PlcStatsSt      `protobuf:"bytes,8,rep,name=police_stats_array,json=policeStatsArray,proto3" json:"police_stats_array,omitempty"`
	WredStatsArray         []*RedProfileStats `protobuf:"bytes,9,rep,name=wred_stats_array,json=wredStatsArray,proto3" json:"wred_stats_array,omitempty"`
	IphcStats              *IphcStatsSt       `protobuf:"bytes,10,opt,name=iphc_stats,json=iphcStats,proto3" json:"iphc_stats,omitempty"`
	ChildPolicy            *QosStats          `protobuf:"bytes,11,opt,name=child_policy,json=childPolicy,proto3" json:"child_policy,omitempty"`
	CacStats               *CacStatsSt        `protobuf:"bytes,12,opt,name=cac_stats,json=cacStats,proto3" json:"cac_stats,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}           `json:"-"`
	XXX_unrecognized       []byte             `json:"-"`
	XXX_sizecache          int32              `json:"-"`
}

func (m *ClassStats) Reset()         { *m = ClassStats{} }
func (m *ClassStats) String() string { return proto.CompactTextString(m) }
func (*ClassStats) ProtoMessage()    {}
func (*ClassStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{10}
}

func (m *ClassStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassStats.Unmarshal(m, b)
}
func (m *ClassStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassStats.Marshal(b, m, deterministic)
}
func (m *ClassStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassStats.Merge(m, src)
}
func (m *ClassStats) XXX_Size() int {
	return xxx_messageInfo_ClassStats.Size(m)
}
func (m *ClassStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassStats.DiscardUnknown(m)
}

var xxx_messageInfo_ClassStats proto.InternalMessageInfo

func (m *ClassStats) GetCounterValidityBitmask() uint64 {
	if m != nil {
		return m.CounterValidityBitmask
	}
	return 0
}

func (m *ClassStats) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *ClassStats) GetSharedQueueId() uint32 {
	if m != nil {
		return m.SharedQueueId
	}
	return 0
}

func (m *ClassStats) GetQueueDescr() string {
	if m != nil {
		return m.QueueDescr
	}
	return ""
}

func (m *ClassStats) GetCacState() string {
	if m != nil {
		return m.CacState
	}
	return ""
}

func (m *ClassStats) GetGeneralStats() *GenStatsSt {
	if m != nil {
		return m.GeneralStats
	}
	return nil
}

func (m *ClassStats) GetQueueStatsArray() []*QStatsSt {
	if m != nil {
		return m.QueueStatsArray
	}
	return nil
}

func (m *ClassStats) GetPoliceStatsArray() []*PlcStatsSt {
	if m != nil {
		return m.PoliceStatsArray
	}
	return nil
}

func (m *ClassStats) GetWredStatsArray() []*RedProfileStats {
	if m != nil {
		return m.WredStatsArray
	}
	return nil
}

func (m *ClassStats) GetIphcStats() *IphcStatsSt {
	if m != nil {
		return m.IphcStats
	}
	return nil
}

func (m *ClassStats) GetChildPolicy() *QosStats {
	if m != nil {
		return m.ChildPolicy
	}
	return nil
}

func (m *ClassStats) GetCacStats() *CacStatsSt {
	if m != nil {
		return m.CacStats
	}
	return nil
}

type QosStats struct {
	PolicyName           string        `protobuf:"bytes,50,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	SubscriberGroup      string        `protobuf:"bytes,51,opt,name=subscriber_group,json=subscriberGroup,proto3" json:"subscriber_group,omitempty"`
	State                string        `protobuf:"bytes,52,opt,name=state,proto3" json:"state,omitempty"`
	StateDescription     string        `protobuf:"bytes,53,opt,name=state_description,json=stateDescription,proto3" json:"state_description,omitempty"`
	ClassStats           []*ClassStats `protobuf:"bytes,54,rep,name=class_stats,json=classStats,proto3" json:"class_stats,omitempty"`
	Satid                uint32        `protobuf:"varint,55,opt,name=satid,proto3" json:"satid,omitempty"`
	PolicyTimestamp      uint64        `protobuf:"varint,56,opt,name=policy_timestamp,json=policyTimestamp,proto3" json:"policy_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QosStats) Reset()         { *m = QosStats{} }
func (m *QosStats) String() string { return proto.CompactTextString(m) }
func (*QosStats) ProtoMessage()    {}
func (*QosStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e45aa6eaecc60a3, []int{11}
}

func (m *QosStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QosStats.Unmarshal(m, b)
}
func (m *QosStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QosStats.Marshal(b, m, deterministic)
}
func (m *QosStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QosStats.Merge(m, src)
}
func (m *QosStats) XXX_Size() int {
	return xxx_messageInfo_QosStats.Size(m)
}
func (m *QosStats) XXX_DiscardUnknown() {
	xxx_messageInfo_QosStats.DiscardUnknown(m)
}

var xxx_messageInfo_QosStats proto.InternalMessageInfo

func (m *QosStats) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *QosStats) GetSubscriberGroup() string {
	if m != nil {
		return m.SubscriberGroup
	}
	return ""
}

func (m *QosStats) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *QosStats) GetStateDescription() string {
	if m != nil {
		return m.StateDescription
	}
	return ""
}

func (m *QosStats) GetClassStats() []*ClassStats {
	if m != nil {
		return m.ClassStats
	}
	return nil
}

func (m *QosStats) GetSatid() uint32 {
	if m != nil {
		return m.Satid
	}
	return 0
}

func (m *QosStats) GetPolicyTimestamp() uint64 {
	if m != nil {
		return m.PolicyTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*QosStats_KEYS)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.qos_stats_KEYS")
	proto.RegisterType((*GenStatsSt)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.gen_stats_st")
	proto.RegisterType((*PolicyParamUint32St_)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.policy_param_uint32_st_")
	proto.RegisterType((*QStatsSt)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.q_stats_st")
	proto.RegisterType((*PlcColorClassStatsSt)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.plc_color_class_stats_st")
	proto.RegisterType((*PlcStatsSt)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.plc_stats_st")
	proto.RegisterType((*WredTypeValue)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.wred_type_value")
	proto.RegisterType((*RedProfileStats)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.red_profile_stats")
	proto.RegisterType((*IphcStatsSt)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.iphc_stats_st")
	proto.RegisterType((*CacStatsSt)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.cac_stats_st")
	proto.RegisterType((*ClassStats)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.class_stats")
	proto.RegisterType((*QosStats)(nil), "cisco_ios_xr_qos_ma_oper.qos.nv_interface_table.interface.nodes.node.output.service_policy_names.service_policy_instance.statistics.qos_stats")
}

func init() { proto.RegisterFile("qos_stats.proto", fileDescriptor_1e45aa6eaecc60a3) }

var fileDescriptor_1e45aa6eaecc60a3 = []byte{
	// 2063 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0xcd, 0x6f, 0x1c, 0x49,
	0x15, 0x57, 0xc7, 0x5f, 0x33, 0x6f, 0x66, 0x3c, 0x33, 0x3d, 0xb1, 0xdd, 0xb6, 0x59, 0x92, 0xcc,
	0x6a, 0xb3, 0xde, 0x65, 0x33, 0xc4, 0xce, 0x42, 0x12, 0x99, 0x15, 0x4a, 0xec, 0xf0, 0x21, 0x36,
	0xec, 0xd2, 0xb1, 0x16, 0x71, 0x6a, 0x95, 0xbb, 0xcb, 0x76, 0x2b, 0xfd, 0xe5, 0xee, 0x9a, 0x59,
	0xfb, 0x0c, 0x67, 0xd8, 0x45, 0x88, 0x13, 0x1c, 0xf8, 0x07, 0x40, 0xca, 0x05, 0x0e, 0x1c, 0xe0,
	0x02, 0x12, 0x17, 0xc4, 0x81, 0xff, 0x81, 0x3b, 0x57, 0x0e, 0xa8, 0xde, 0xab, 0xee, 0xa9, 0xee,
	0x69, 0x2f, 0x89, 0xc4, 0x61, 0x72, 0xb1, 0xdc, 0xef, 0xfd, 0xde, 0x67, 0xbd, 0x7a, 0xaf, 0xaa,
	0x06, 0xba, 0xe7, 0x71, 0xe6, 0x64, 0x82, 0x89, 0x6c, 0x94, 0xa4, 0xb1, 0x88, 0xcd, 0x1f, 0x1b,
	0xae, 0x9f, 0xb9, 0xb1, 0xe3, 0xc7, 0x99, 0x73, 0x91, 0x3a, 0x92, 0x1d, 0x32, 0x27, 0x4e, 0x78,
	0x3a, 0x3a, 0x8f, 0xb3, 0x51, 0x34, 0x71, 0xfc, 0x48, 0xf0, 0xf4, 0x84, 0xb9, 0xdc, 0x11, 0xec,
	0x38, 0xe0, 0xa3, 0xe2, 0x7b, 0x14, 0xc5, 0x1e, 0xcf, 0xf0, 0xef, 0x28, 0x1e, 0x8b, 0x64, 0x2c,
	0x46, 0x19, 0x4f, 0x27, 0xbe, 0xcb, 0x9d, 0x24, 0x0e, 0x7c, 0xf7, 0xd2, 0x89, 0x58, 0xc8, 0xb3,
	0x2a, 0xd1, 0x8f, 0x32, 0xc1, 0x22, 0x97, 0x8f, 0xa4, 0x1b, 0x7e, 0x26, 0x7c, 0x37, 0x1b, 0xfe,
	0xc4, 0x80, 0xd5, 0xc2, 0x33, 0xe7, 0x7b, 0x4f, 0x7e, 0xf4, 0xcc, 0x7c, 0x0b, 0x56, 0xa7, 0x96,
	0xa5, 0x22, 0xcb, 0xb8, 0x69, 0xec, 0x34, 0xed, 0x4e, 0x41, 0xfd, 0x3e, 0x0b, 0xb9, 0xb9, 0x0d,
	0x4d, 0xe9, 0x00, 0x21, 0xae, 0x21, 0xa2, 0x21, 0x09, 0xc8, 0x1c, 0xc1, 0xa0, 0xc6, 0x23, 0x6b,
	0x01, 0x61, 0x7d, 0xc5, 0xfa, 0x18, 0x39, 0x12, 0x3f, 0xfc, 0xed, 0x02, 0xb4, 0x4f, 0x79, 0xa4,
	0xdc, 0xc8, 0x84, 0xf9, 0x0e, 0xf4, 0x44, 0xca, 0xa2, 0x2c, 0xf4, 0x85, 0x93, 0x30, 0xf7, 0x39,
	0x17, 0x19, 0xba, 0xb1, 0x68, 0x77, 0x73, 0xfa, 0xc7, 0x44, 0x96, 0xfe, 0x16, 0xd0, 0xe3, 0x4b,
	0xc1, 0x33, 0xf4, 0x66, 0xd1, 0xee, 0xe4, 0xd4, 0xc7, 0x92, 0x68, 0xbe, 0x07, 0xa6, 0x88, 0x05,
	0x0b, 0x1c, 0x2f, 0x8d, 0x93, 0x42, 0xe7, 0x02, 0x42, 0x7b, 0xc8, 0x39, 0x4c, 0xe3, 0x24, 0x57,
	0xba, 0x03, 0x3d, 0x0d, 0x4d, 0x6a, 0x17, 0x11, 0xbb, 0x5a, 0x60, 0x49, 0xef, 0x6d, 0xe8, 0x6a,
	0xc8, 0x94, 0x09, 0x6e, 0x2d, 0xdd, 0x34, 0x76, 0x3a, 0x76, 0xa7, 0x00, 0xda, 0x4c, 0x70, 0x89,
	0x0b, 0x99, 0x70, 0xcf, 0x1c, 0x8f, 0x09, 0x46, 0xb8, 0x65, 0xc2, 0x21, 0xf9, 0x90, 0x09, 0x86,
	0xb8, 0x11, 0x0c, 0x48, 0x5f, 0x11, 0x14, 0x62, 0x57, 0x10, 0xdb, 0x47, 0xd6, 0x91, 0xe2, 0x20,
	0x7e, 0x1f, 0xb6, 0x92, 0xb4, 0x48, 0x33, 0xea, 0xe2, 0x5e, 0x11, 0x5f, 0x03, 0x7d, 0xde, 0x48,
	0x52, 0x95, 0xed, 0xa7, 0xc4, 0xcf, 0xc3, 0xbc, 0x0f, 0x56, 0x8d, 0x30, 0x85, 0xdb, 0x44, 0xd1,
	0xb5, 0xaa, 0x28, 0x46, 0x3d, 0x3c, 0x80, 0x0d, 0x25, 0x94, 0xb0, 0x94, 0x85, 0xce, 0xd8, 0x8f,
	0xc4, 0xbd, 0x3d, 0x27, 0x13, 0x8e, 0x79, 0x1d, 0x96, 0x26, 0x2c, 0x18, 0x53, 0xd9, 0x74, 0x6c,
	0xfa, 0x30, 0x4d, 0x58, 0x1c, 0x47, 0xbe, 0x50, 0x95, 0x82, 0xff, 0x0f, 0xff, 0xd0, 0x02, 0x38,
	0x9f, 0xae, 0xf9, 0x26, 0x34, 0xce, 0xc7, 0x7c, 0xcc, 0x1d, 0xdf, 0x53, 0xb2, 0x2b, 0xf8, 0xfd,
	0x5d, 0xcf, 0x7c, 0x17, 0xfa, 0x82, 0xf9, 0x95, 0xb5, 0xbb, 0xa6, 0xea, 0x81, 0xf9, 0xa5, 0xa5,
	0x93, 0x0b, 0x52, 0x60, 0x29, 0x94, 0x05, 0x55, 0x10, 0x0a, 0x49, 0x0b, 0xb7, 0x0b, 0x6b, 0x4c,
	0x84, 0x8e, 0x1b, 0x24, 0x77, 0xcb, 0x7a, 0x69, 0x9d, 0x4d, 0x26, 0xc2, 0x83, 0x20, 0xb9, 0xab,
	0xab, 0xbe, 0x03, 0x83, 0xb2, 0x08, 0xa9, 0x5f, 0xa2, 0x22, 0xd2, 0x04, 0xaa, 0x16, 0x76, 0xcb,
	0x16, 0x96, 0x75, 0x0b, 0xbb, 0xf5, 0x16, 0x76, 0x75, 0x0b, 0x2b, 0xba, 0x85, 0xdd, 0xa9, 0x85,
	0x7f, 0x18, 0xb0, 0xa6, 0x72, 0xa6, 0x36, 0xb7, 0x13, 0xf0, 0xe8, 0x54, 0x9c, 0x59, 0x8d, 0x9b,
	0x0b, 0x3b, 0xad, 0xbd, 0x5f, 0x19, 0xa3, 0x39, 0xe8, 0x32, 0xa3, 0x2b, 0x4a, 0xc5, 0x1e, 0xd0,
	0xfa, 0x2a, 0x89, 0x0f, 0xd1, 0x73, 0xf3, 0xef, 0x06, 0x5c, 0xa7, 0x98, 0xd8, 0x84, 0xa7, 0xec,
	0xb4, 0x08, 0xa9, 0xf9, 0x3a, 0x84, 0x64, 0xa2, 0xeb, 0x8f, 0xc8, 0x73, 0x15, 0xd1, 0x5f, 0x0d,
	0xe8, 0x51, 0x44, 0x21, 0xbb, 0xc8, 0xa3, 0x81, 0xd7, 0x21, 0x9a, 0x55, 0x74, 0xfb, 0x29, 0xbb,
	0x50, 0x91, 0xdc, 0xcd, 0x97, 0x06, 0x6b, 0x53, 0x9c, 0xa5, 0x3c, 0x3b, 0x8b, 0x03, 0xcf, 0x6a,
	0xe1, 0x76, 0xa5, 0xd8, 0x65, 0x75, 0x1e, 0xe5, 0x1c, 0xf3, 0x21, 0x6c, 0x9e, 0xc4, 0xa9, 0xcb,
	0x3d, 0xe7, 0xd3, 0x94, 0x7b, 0x6a, 0xb3, 0x7b, 0x7e, 0x96, 0x04, 0xec, 0xd2, 0x6a, 0xdf, 0x34,
	0x76, 0x1a, 0xf6, 0x3a, 0x01, 0x7e, 0x98, 0x72, 0xef, 0x99, 0x64, 0x1f, 0x12, 0x57, 0x76, 0xc2,
	0x94, 0x45, 0x5e, 0x1c, 0x96, 0x37, 0x4f, 0x07, 0xf7, 0x42, 0x9f, 0x58, 0xfa, 0xde, 0x79, 0x17,
	0xfa, 0x3a, 0x9e, 0x76, 0xce, 0x2a, 0x35, 0x89, 0x29, 0x9a, 0x36, 0xce, 0x1e, 0xac, 0xc9, 0xb5,
	0x28, 0x22, 0x28, 0xb4, 0x77, 0x11, 0x3f, 0x08, 0xd9, 0x45, 0x11, 0x43, 0xae, 0x7f, 0x04, 0x83,
	0xb2, 0x0c, 0x59, 0xe8, 0x91, 0x3f, 0xba, 0x04, 0xd9, 0x78, 0x1b, 0xba, 0x6e, 0x1c, 0x9d, 0xc4,
	0x69, 0x58, 0x68, 0xef, 0xd3, 0x08, 0x51, 0xe4, 0x5c, 0xf1, 0x9b, 0xd0, 0xc9, 0x81, 0xa4, 0xd2,
	0x44, 0x58, 0x5b, 0x11, 0x49, 0xdb, 0x5b, 0xb0, 0xca, 0x2f, 0x5c, 0xae, 0xf5, 0xf6, 0x01, 0x75,
	0x35, 0xa2, 0xe6, 0xba, 0x6e, 0x41, 0x5b, 0xc1, 0x48, 0xd5, 0x75, 0x04, 0xb5, 0x88, 0x46, 0x9a,
	0x6e, 0x41, 0xae, 0x99, 0x46, 0xcb, 0x1a, 0x2e, 0x5e, 0x4b, 0xd1, 0x70, 0xa8, 0xdc, 0x00, 0x25,
	0x41, 0x88, 0x75, 0x44, 0x00, 0x91, 0x24, 0x60, 0xf8, 0x9f, 0x06, 0x58, 0x49, 0xe0, 0x3a, 0x6e,
	0x1c, 0xc4, 0xa9, 0xe3, 0x06, 0x2c, 0xcb, 0xa6, 0x8d, 0xfc, 0x11, 0xbc, 0x91, 0x1b, 0x20, 0x4e,
	0x35, 0x0d, 0x34, 0xc9, 0xb7, 0x14, 0xf9, 0x40, 0x62, 0x0e, 0xca, 0x29, 0xf9, 0x00, 0xb6, 0xeb,
	0x55, 0xe8, 0x13, 0xde, 0xaa, 0x51, 0x40, 0x21, 0xee, 0xc3, 0x56, 0xbd, 0x38, 0x86, 0xb3, 0x80,
	0xe1, 0x6c, 0xd4, 0x48, 0x63, 0xf0, 0xdf, 0x84, 0x2f, 0x95, 0x85, 0x2b, 0x79, 0xa7, 0xf9, 0xb0,
	0xa9, 0x8b, 0x3f, 0x29, 0xad, 0xc1, 0x8c, 0xf5, 0xd2, 0x8a, 0xd0, 0xb4, 0xd8, 0x98, 0x15, 0x27,
	0xd7, 0x1f, 0xc2, 0x66, 0xad, 0xb0, 0x76, 0x62, 0x58, 0x9f, 0x95, 0x45, 0xc7, 0x67, 0xf2, 0x3e,
	0xf1, 0xe3, 0x80, 0x09, 0x5e, 0x78, 0xbe, 0x32, 0x9b, 0xf7, 0x4f, 0x08, 0x72, 0x65, 0xde, 0x73,
	0x15, 0xe4, 0x7b, 0x63, 0x36, 0xef, 0x4a, 0xc1, 0x15, 0x79, 0xcf, 0xc5, 0xd1, 0xfb, 0xe6, 0x6c,
	0xde, 0x95, 0x34, 0xba, 0xff, 0x01, 0x6c, 0xab, 0x58, 0x6b, 0xd3, 0x0e, 0x64, 0x9b, 0xa8, 0x35,
	0x59, 0x7f, 0x08, 0x9b, 0x75, 0xe2, 0xe4, 0x78, 0x0b, 0x85, 0xd7, 0x67, 0x84, 0xc9, 0xed, 0xfb,
	0x60, 0xd5, 0x89, 0xa2, 0xd3, 0x6d, 0x74, 0x7a, 0x6d, 0x46, 0x32, 0x2f, 0x95, 0x92, 0x60, 0x35,
	0xe1, 0xd4, 0xab, 0x36, 0x35, 0xe1, 0x4a, 0xbe, 0xf7, 0x61, 0xab, 0x56, 0x81, 0xde, 0xbc, 0x36,
	0x66, 0xc5, 0x8b, 0x52, 0xa9, 0x15, 0x46, 0xbf, 0xbb, 0x54, 0x2a, 0xb3, 0xb2, 0x79, 0xa9, 0xe4,
	0xe8, 0x7a, 0xcf, 0xa9, 0xab, 0x6d, 0x29, 0xf2, 0x15, 0xa5, 0x52, 0xaf, 0x82, 0x7c, 0xa7, 0x56,
	0x67, 0xd5, 0x28, 0x28, 0x4a, 0xa5, 0x5e, 0x1c, 0xbd, 0x37, 0xa9, 0x54, 0x6a, 0xa4, 0xb1, 0xfd,
	0xfc, 0x65, 0x09, 0xda, 0xb2, 0xfd, 0x14, 0x2d, 0xe7, 0x16, 0xb4, 0x4b, 0x43, 0x82, 0x3a, 0x4c,
	0xcb, 0xd3, 0xc6, 0xc3, 0x1b, 0x00, 0xda, 0x5c, 0xa0, 0x0e, 0xd2, 0xf4, 0x8a, 0x89, 0x50, 0xd3,
	0xad, 0x17, 0x5e, 0xae, 0x5b, 0x2f, 0xbe, 0x54, 0xb7, 0x5e, 0x7a, 0x99, 0x6e, 0xbd, 0x3c, 0xdb,
	0xad, 0xdf, 0x86, 0x6e, 0xfd, 0x36, 0x5e, 0x9d, 0x94, 0xd7, 0xe3, 0x4d, 0xe8, 0xd4, 0x6d, 0xd6,
	0xf6, 0x44, 0xcf, 0xfa, 0x08, 0x06, 0x09, 0x4b, 0x79, 0x24, 0xca, 0x33, 0x95, 0xce, 0xfa, 0x7d,
	0x62, 0x55, 0x66, 0xaa, 0x8e, 0x27, 0xc5, 0xb4, 0x13, 0xbb, 0x53, 0x74, 0xfd, 0x5c, 0x69, 0xfd,
	0xcf, 0xb9, 0xd2, 0xae, 0xce, 0x15, 0xa9, 0xa3, 0x54, 0x07, 0x1d, 0xd2, 0x31, 0xd1, 0x4a, 0xf7,
	0x6f, 0x06, 0xf4, 0x67, 0xc6, 0x0e, 0x6e, 0x95, 0xd6, 0xde, 0xaf, 0xe7, 0xe4, 0x38, 0x75, 0xc5,
	0x64, 0xb4, 0xbb, 0x48, 0xc5, 0x72, 0xc6, 0xa3, 0xce, 0xf0, 0x10, 0xba, 0x78, 0x2e, 0x12, 0x97,
	0x09, 0x77, 0xe8, 0xa6, 0xb4, 0x0d, 0xcd, 0x82, 0xa4, 0xae, 0xde, 0x0d, 0x49, 0x38, 0xba, 0x4c,
	0xf8, 0xf4, 0x72, 0x75, 0x4d, 0xbb, 0x5c, 0x0d, 0xff, 0xbd, 0x08, 0x7d, 0x29, 0x92, 0xa4, 0xf1,
	0x89, 0x1f, 0x70, 0xb2, 0x27, 0x0b, 0x22, 0x27, 0x08, 0x5f, 0x04, 0xb9, 0xb2, 0xb6, 0x22, 0x1e,
	0x49, 0x9a, 0xf9, 0xc2, 0x80, 0xa6, 0x14, 0x0d, 0xd8, 0x31, 0x0f, 0xac, 0x6b, 0x78, 0x28, 0xfd,
	0xc5, 0x7c, 0x64, 0xb1, 0x92, 0x18, 0xbb, 0x91, 0x72, 0xef, 0x43, 0xe9, 0xa6, 0x3c, 0x86, 0x22,
	0xaf, 0xfa, 0x42, 0x40, 0x1b, 0xd6, 0x94, 0xc9, 0xaa, 0x3c, 0x12, 0xbc, 0x07, 0x66, 0x49, 0x42,
	0xdf, 0xb9, 0x3d, 0x0d, 0x5f, 0xec, 0x92, 0xba, 0x93, 0xe7, 0xd2, 0x2b, 0x9d, 0x3c, 0x97, 0x5f,
	0xf1, 0xe4, 0xb9, 0xf2, 0xca, 0x27, 0xcf, 0xc6, 0x55, 0x27, 0xcf, 0x7b, 0xb0, 0x2e, 0xa3, 0xe5,
	0x6e, 0xe4, 0x84, 0x2c, 0x7d, 0xae, 0x75, 0x21, 0xda, 0xe8, 0x83, 0x94, 0x7b, 0x4f, 0xdc, 0xe8,
	0x29, 0xf2, 0x72, 0x23, 0x5f, 0xa5, 0xa4, 0x6a, 0x42, 0xfa, 0x6e, 0xef, 0xeb, 0x22, 0xf4, 0x06,
	0xf0, 0x9b, 0x25, 0xe8, 0xf8, 0xc9, 0x99, 0xd6, 0x85, 0x1f, 0xc0, 0x66, 0x14, 0x47, 0x8e, 0x70,
	0x13, 0x87, 0xde, 0x30, 0xe2, 0x71, 0xf5, 0xf9, 0x66, 0x2d, 0x8a, 0xa3, 0x23, 0x37, 0x39, 0x92,
	0xec, 0x8f, 0xc6, 0xc5, 0xfa, 0xbc, 0x0f, 0x1b, 0xb3, 0x92, 0x7a, 0xa7, 0x1e, 0x94, 0xe5, 0x28,
	0xce, 0x3b, 0x30, 0xc8, 0xa5, 0x10, 0xeb, 0x64, 0x6c, 0xc2, 0xbd, 0xfc, 0x51, 0x87, 0x24, 0x10,
	0xf9, 0x4c, 0xd2, 0xcd, 0xc7, 0xf0, 0xe5, 0x1c, 0xee, 0xc6, 0x61, 0x92, 0xf2, 0x2c, 0x9b, 0xa6,
	0x46, 0x5a, 0x54, 0x05, 0xb1, 0x45, 0x92, 0x07, 0x05, 0x46, 0x79, 0xf9, 0xd1, 0x58, 0xe8, 0x8e,
	0x2a, 0x93, 0xb2, 0x39, 0x6a, 0xcf, 0x3e, 0x03, 0xdd, 0x2c, 0x8f, 0xe8, 0x91, 0xe6, 0x00, 0x6e,
	0xe4, 0x52, 0x27, 0xe3, 0x20, 0x70, 0xce, 0x38, 0xf3, 0x78, 0x5a, 0x32, 0xbd, 0xac, 0x9b, 0xfe,
	0xd6, 0x38, 0x08, 0xbe, 0x83, 0x18, 0xcd, 0xf4, 0x2e, 0xac, 0xd5, 0x67, 0x96, 0x2a, 0xc7, 0x14,
	0xb3, 0x69, 0xbd, 0x03, 0x83, 0xba, 0x94, 0x36, 0xd4, 0xab, 0x57, 0x35, 0x9f, 0xb7, 0xa1, 0x5b,
	0xcd, 0x65, 0x53, 0x3d, 0x9d, 0x94, 0x12, 0xb9, 0x0f, 0x5b, 0x5f, 0x90, 0x44, 0x2a, 0x98, 0x0d,
	0x71, 0x45, 0x06, 0x95, 0x4f, 0xd5, 0xec, 0xd1, 0xb4, 0xe8, 0x89, 0x6a, 0xea, 0xbe, 0x01, 0xdb,
	0x5f, 0x94, 0xb6, 0x76, 0x61, 0xac, 0x2e, 0x67, 0xc3, 0x7f, 0x1a, 0xd0, 0x76, 0xd9, 0xff, 0xf5,
	0xa0, 0x90, 0xb3, 0xa5, 0xd7, 0x99, 0xba, 0x4b, 0x20, 0x5b, 0xba, 0x9b, 0x99, 0x43, 0x68, 0x33,
	0x2f, 0xf4, 0x45, 0xf9, 0xb6, 0x50, 0xa2, 0xc9, 0x31, 0x88, 0xdf, 0xa5, 0x1b, 0x01, 0x20, 0x89,
	0x6c, 0x14, 0x00, 0x32, 0x42, 0xc7, 0x7e, 0x02, 0xa0, 0x95, 0xe1, 0xbf, 0x5a, 0xd0, 0xd2, 0x66,
	0x8b, 0xf9, 0x00, 0x2c, 0x37, 0x1e, 0xcb, 0x26, 0x2c, 0x9b, 0xa5, 0xef, 0xf9, 0xe2, 0xd2, 0x39,
	0xf6, 0x45, 0xc8, 0xb2, 0xe7, 0x2a, 0xc4, 0x75, 0xc5, 0xff, 0x44, 0xb1, 0x1f, 0x13, 0x57, 0x86,
	0x43, 0x8a, 0xb4, 0x87, 0xdc, 0x26, 0x52, 0xf0, 0x25, 0xf7, 0x36, 0x74, 0xb3, 0x33, 0x26, 0x1b,
	0x43, 0xf1, 0x36, 0x47, 0x21, 0x77, 0x88, 0xfc, 0x03, 0xf5, 0x42, 0x77, 0x03, 0x5a, 0xea, 0x65,
	0x80, 0x67, 0x6e, 0x8a, 0x51, 0x37, 0x6d, 0xa0, 0x07, 0x01, 0x49, 0x91, 0x63, 0x2d, 0x5f, 0x08,
	0xda, 0x2a, 0x4d, 0xbb, 0xe1, 0x32, 0x57, 0x8e, 0x41, 0x6e, 0xfe, 0xde, 0x80, 0xce, 0x29, 0x8f,
	0x78, 0xca, 0x02, 0x35, 0xcf, 0x97, 0x71, 0x9e, 0x7f, 0x3e, 0x1f, 0x93, 0x48, 0x7f, 0x9a, 0xb6,
	0xdb, 0xca, 0x51, 0x1c, 0xe0, 0xe6, 0x1f, 0x0d, 0xe8, 0x53, 0xe0, 0x04, 0x60, 0x69, 0xca, 0x2e,
	0xad, 0x15, 0x9c, 0xa3, 0x3f, 0x9b, 0x0f, 0xef, 0xcf, 0xb5, 0xf3, 0x07, 0xba, 0x8a, 0x9e, 0x3f,
	0x92, 0x8e, 0x9a, 0x7f, 0x32, 0xc0, 0x44, 0xd1, 0xb2, 0xff, 0xf4, 0x7a, 0xf8, 0xf9, 0xfc, 0x9c,
	0xa6, 0x8a, 0x08, 0x7a, 0xe4, 0xad, 0x16, 0xc2, 0x9f, 0x0d, 0xe8, 0x69, 0x6f, 0x4b, 0x14, 0x00,
	0xbd, 0x15, 0xfe, 0x72, 0x3e, 0x02, 0x98, 0x39, 0x9a, 0xd9, 0xab, 0x9f, 0xe6, 0x8f, 0x5d, 0x14,
	0xc3, 0x0b, 0x03, 0x60, 0x3a, 0x4a, 0xb1, 0x83, 0xb6, 0xf6, 0x7e, 0x3e, 0x1f, 0xde, 0x97, 0x46,
	0xbc, 0xdd, 0x94, 0x9f, 0x54, 0xfa, 0x2f, 0x64, 0x6f, 0x3d, 0xf3, 0xe5, 0x11, 0x06, 0xa5, 0xb1,
	0x85, 0xb7, 0xf6, 0x7e, 0x3a, 0x27, 0x55, 0x9f, 0xff, 0xaa, 0x65, 0xb7, 0xd0, 0x49, 0xfa, 0x11,
	0xc3, 0xfc, 0x9d, 0x31, 0xed, 0x43, 0x19, 0x4e, 0x8f, 0xb9, 0xa9, 0x73, 0x7d, 0x4e, 0x15, 0xbd,
	0x31, 0x1b, 0x7e, 0xb6, 0x00, 0xcd, 0x22, 0x18, 0xd9, 0x67, 0xf5, 0x5f, 0xd4, 0xf6, 0xa8, 0xcf,
	0x26, 0xc5, 0x4f, 0x69, 0xe6, 0x3b, 0xd0, 0xcb, 0xc6, 0xc7, 0x99, 0x9b, 0xfa, 0xc7, 0x3c, 0x75,
	0x4e, 0xd3, 0x78, 0x9c, 0x58, 0xf7, 0x10, 0xd5, 0x9d, 0xd2, 0xbf, 0x2d, 0xc9, 0xf2, 0x32, 0x41,
	0xed, 0xf8, 0x7d, 0xe4, 0xd3, 0x87, 0xf9, 0x15, 0xe8, 0xe3, 0x3f, 0xd4, 0xc9, 0xfd, 0x44, 0xf8,
	0x71, 0x64, 0x7d, 0x0d, 0x11, 0x3d, 0x64, 0x1c, 0x4e, 0xe9, 0xb2, 0x06, 0xf4, 0x39, 0x64, 0x7d,
	0x1d, 0xf7, 0xdd, 0x67, 0x73, 0x92, 0xd0, 0xa9, 0x63, 0x36, 0x0d, 0x39, 0x2a, 0x5c, 0x19, 0x37,
	0x13, 0xbe, 0x67, 0xdd, 0xa7, 0x4b, 0x14, 0x7e, 0xc8, 0xc4, 0x29, 0x5d, 0xc2, 0x0f, 0x79, 0x26,
	0x58, 0x98, 0x58, 0x0f, 0xd4, 0x4d, 0x17, 0xe9, 0x47, 0x39, 0xf9, 0x78, 0x19, 0x7f, 0xc2, 0xbd,
	0xf7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x6c, 0x3f, 0x00, 0xd5, 0x1d, 0x00, 0x00,
}
